export interface CountryInterface {
            'commonName': string;
            'officialName': string;
            'region': string;
            'subRegion': string;
            'iso2': string;
            'iso3': string;
    }

export class Countries {
    CountryList(): CountryInterface[] {
        return [
            {
                'commonName': 'Aruba',
                'officialName': 'Aruba',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'AW',
                'iso3': 'ABW',
            },
            {
                'commonName': 'Afghanistan',
                'officialName': 'Islamic Republic of Afghanistan',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'AF',
                'iso3': 'AFG',
            },
            {
                'commonName': 'Angola',
                'officialName': 'Republic of Angola',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'AO',
                'iso3': 'AGO',
            },
            {
                'commonName': 'Anguilla',
                'officialName': 'Anguilla',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'AI',
                'iso3': 'AIA',
            },
            {
                'commonName': 'Åland Islands',
                'officialName': 'Åland Islands',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'AX',
                'iso3': 'ALA',
            },
            {
                'commonName': 'Albania',
                'officialName': 'Republic of Albania',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'AL',
                'iso3': 'ALB',
            },
            {
                'commonName': 'Andorra',
                'officialName': 'Principality of Andorra',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'AD',
                'iso3': 'AND',
            },
            {
                'commonName': 'United Arab Emirates',
                'officialName': 'United Arab Emirates',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'AE',
                'iso3': 'ARE',
            },
            {
                'commonName': 'Argentina',
                'officialName': 'Argentine Republic',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'AR',
                'iso3': 'ARG',
            },
            {
                'commonName': 'Armenia',
                'officialName': 'Republic of Armenia',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'AM',
                'iso3': 'ARM',
            },
            {
                'commonName': 'American Samoa',
                'officialName': 'American Samoa',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'AS',
                'iso3': 'ASM',
            },
            {
                'commonName': 'Antarctica',
                'officialName': 'Antarctica',
                'region': '',
                'subRegion': '',
                'iso2': 'AQ',
                'iso3': 'ATA',
            },
            {
                'commonName': 'French Southern and Antarctic Lands',
                'officialName': 'Territory of the French Southern and Antarctic Lands',
                'region': '',
                'subRegion': '',
                'iso2': 'TF',
                'iso3': 'ATF',
            },
            {
                'commonName': 'Antigua and Barbuda',
                'officialName': 'Antigua and Barbuda',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'AG',
                'iso3': 'ATG',
            },
            {
                'commonName': 'Australia',
                'officialName': 'Commonwealth of Australia',
                'region': 'Oceania',
                'subRegion': 'Australia and New Zealand',
                'iso2': 'AU',
                'iso3': 'AUS',
            },
            {
                'commonName': 'Austria',
                'officialName': 'Republic of Austria',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'AT',
                'iso3': 'AUT',
            },
            {
                'commonName': 'Azerbaijan',
                'officialName': 'Republic of Azerbaijan',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'AZ',
                'iso3': 'AZE',
            },
            {
                'commonName': 'Burundi',
                'officialName': 'Republic of Burundi',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'BI',
                'iso3': 'BDI',
            },
            {
                'commonName': 'Belgium',
                'officialName': 'Kingdom of Belgium',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'BE',
                'iso3': 'BEL',
            },
            {
                'commonName': 'Benin',
                'officialName': 'Republic of Benin',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'BJ',
                'iso3': 'BEN',
            },
            {
                'commonName': 'Burkina Faso',
                'officialName': 'Burkina Faso',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'BF',
                'iso3': 'BFA',
            },
            {
                'commonName': 'Bangladesh',
                'officialName': 'People&#039;s Republic of Bangladesh',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'BD',
                'iso3': 'BGD',
            },
            {
                'commonName': 'Bulgaria',
                'officialName': 'Republic of Bulgaria',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'BG',
                'iso3': 'BGR',
            },
            {
                'commonName': 'Bahrain',
                'officialName': 'Kingdom of Bahrain',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'BH',
                'iso3': 'BHR',
            },
            {
                'commonName': 'Bahamas',
                'officialName': 'Commonwealth of the Bahamas',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'BS',
                'iso3': 'BHS',
            },
            {
                'commonName': 'Bosnia and Herzegovina',
                'officialName': 'Bosnia and Herzegovina',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'BA',
                'iso3': 'BIH',
            },
            {
                'commonName': 'Saint Barthélemy',
                'officialName': 'Collectivity of Saint Barthélemy',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'BL',
                'iso3': 'BLM',
            },
            {
                'commonName': 'Belarus',
                'officialName': 'Republic of Belarus',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'BY',
                'iso3': 'BLR',
            },
            {
                'commonName': 'Belize',
                'officialName': 'Belize',
                'region': 'Americas',
                'subRegion': 'Central America',
                'iso2': 'BZ',
                'iso3': 'BLZ',
            },
            {
                'commonName': 'Bermuda',
                'officialName': 'Bermuda',
                'region': 'Americas',
                'subRegion': 'Northern America',
                'iso2': 'BM',
                'iso3': 'BMU',
            },
            {
                'commonName': 'Bolivia',
                'officialName': 'Plurinational State of Bolivia',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'BO',
                'iso3': 'BOL',
            },
            {
                'commonName': 'Brazil',
                'officialName': 'Federative Republic of Brazil',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'BR',
                'iso3': 'BRA',
            },
            {
                'commonName': 'Barbados',
                'officialName': 'Barbados',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'BB',
                'iso3': 'BRB',
            },
            {
                'commonName': 'Brunei',
                'officialName': 'Nation of Brunei, Abode of Peace',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'BN',
                'iso3': 'BRN',
            },
            {
                'commonName': 'Bhutan',
                'officialName': 'Kingdom of Bhutan',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'BT',
                'iso3': 'BTN',
            },
            {
                'commonName': 'Bouvet Island',
                'officialName': 'Bouvet Island',
                'region': '',
                'subRegion': '',
                'iso2': 'BV',
                'iso3': 'BVT',
            },
            {
                'commonName': 'Botswana',
                'officialName': 'Republic of Botswana',
                'region': 'Africa',
                'subRegion': 'Southern Africa',
                'iso2': 'BW',
                'iso3': 'BWA',
            },
            {
                'commonName': 'Central African Republic',
                'officialName': 'Central African Republic',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'CF',
                'iso3': 'CAF',
            },
            {
                'commonName': 'Canada',
                'officialName': 'Canada',
                'region': 'Americas',
                'subRegion': 'Northern America',
                'iso2': 'CA',
                'iso3': 'CAN',
            },
            {
                'commonName': 'Cocos (Keeling) Islands',
                'officialName': 'Territory of the Cocos (Keeling) Islands',
                'region': 'Oceania',
                'subRegion': 'Australia and New Zealand',
                'iso2': 'CC',
                'iso3': 'CCK',
            },
            {
                'commonName': 'Switzerland',
                'officialName': 'Swiss Confederation',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'CH',
                'iso3': 'CHE',
            },
            {
                'commonName': 'Chile',
                'officialName': 'Republic of Chile',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'CL',
                'iso3': 'CHL',
            },
            {
                'commonName': 'China',
                'officialName': 'People&#039;s Republic of China',
                'region': 'Asia',
                'subRegion': 'Eastern Asia',
                'iso2': 'CN',
                'iso3': 'CHN',
            },
            {
                'commonName': 'Ivory Coast',
                'officialName': 'Republic of Côte d&#039;Ivoire',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'CI',
                'iso3': 'CIV',
            },
            {
                'commonName': 'Cameroon',
                'officialName': 'Republic of Cameroon',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'CM',
                'iso3': 'CMR',
            },
            {
                'commonName': 'DR Congo',
                'officialName': 'Democratic Republic of the Congo',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'CD',
                'iso3': 'COD',
            },
            {
                'commonName': 'Republic of the Congo',
                'officialName': 'Republic of the Congo',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'CG',
                'iso3': 'COG',
            },
            {
                'commonName': 'Cook Islands',
                'officialName': 'Cook Islands',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'CK',
                'iso3': 'COK',
            },
            {
                'commonName': 'Colombia',
                'officialName': 'Republic of Colombia',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'CO',
                'iso3': 'COL',
            },
            {
                'commonName': 'Comoros',
                'officialName': 'Union of the Comoros',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'KM',
                'iso3': 'COM',
            },
            {
                'commonName': 'Cape Verde',
                'officialName': 'Republic of Cabo Verde',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'CV',
                'iso3': 'CPV',
            },
            {
                'commonName': 'Costa Rica',
                'officialName': 'Republic of Costa Rica',
                'region': 'Americas',
                'subRegion': 'Central America',
                'iso2': 'CR',
                'iso3': 'CRI',
            },
            {
                'commonName': 'Cuba',
                'officialName': 'Republic of Cuba',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'CU',
                'iso3': 'CUB',
            },
            {
                'commonName': 'Curaçao',
                'officialName': 'Country of Curaçao',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'CW',
                'iso3': 'CUW',
            },
            {
                'commonName': 'Christmas Island',
                'officialName': 'Territory of Christmas Island',
                'region': 'Oceania',
                'subRegion': 'Australia and New Zealand',
                'iso2': 'CX',
                'iso3': 'CXR',
            },
            {
                'commonName': 'Cayman Islands',
                'officialName': 'Cayman Islands',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'KY',
                'iso3': 'CYM',
            },
            {
                'commonName': 'Cyprus',
                'officialName': 'Republic of Cyprus',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'CY',
                'iso3': 'CYP',
            },
            {
                'commonName': 'Czechia',
                'officialName': 'Czech Republic',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'CZ',
                'iso3': 'CZE',
            },
            {
                'commonName': 'Germany',
                'officialName': 'Federal Republic of Germany',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'DE',
                'iso3': 'DEU',
            },
            {
                'commonName': 'Djibouti',
                'officialName': 'Republic of Djibouti',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'DJ',
                'iso3': 'DJI',
            },
            {
                'commonName': 'Dominica',
                'officialName': 'Commonwealth of Dominica',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'DM',
                'iso3': 'DMA',
            },
            {
                'commonName': 'Denmark',
                'officialName': 'Kingdom of Denmark',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'DK',
                'iso3': 'DNK',
            },
            {
                'commonName': 'Dominican Republic',
                'officialName': 'Dominican Republic',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'DO',
                'iso3': 'DOM',
            },
            {
                'commonName': 'Algeria',
                'officialName': 'People&#039;s Democratic Republic of Algeria',
                'region': 'Africa',
                'subRegion': 'Northern Africa',
                'iso2': 'DZ',
                'iso3': 'DZA',
            },
            {
                'commonName': 'Ecuador',
                'officialName': 'Republic of Ecuador',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'EC',
                'iso3': 'ECU',
            },
            {
                'commonName': 'Egypt',
                'officialName': 'Arab Republic of Egypt',
                'region': 'Africa',
                'subRegion': 'Northern Africa',
                'iso2': 'EG',
                'iso3': 'EGY',
            },
            {
                'commonName': 'Eritrea',
                'officialName': 'State of Eritrea',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'ER',
                'iso3': 'ERI',
            },
            {
                'commonName': 'Western Sahara',
                'officialName': 'Sahrawi Arab Democratic Republic',
                'region': 'Africa',
                'subRegion': 'Northern Africa',
                'iso2': 'EH',
                'iso3': 'ESH',
            },
            {
                'commonName': 'Spain',
                'officialName': 'Kingdom of Spain',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'ES',
                'iso3': 'ESP',
            },
            {
                'commonName': 'Estonia',
                'officialName': 'Republic of Estonia',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'EE',
                'iso3': 'EST',
            },
            {
                'commonName': 'Ethiopia',
                'officialName': 'Federal Democratic Republic of Ethiopia',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'ET',
                'iso3': 'ETH',
            },
            {
                'commonName': 'Finland',
                'officialName': 'Republic of Finland',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'FI',
                'iso3': 'FIN',
            },
            {
                'commonName': 'Fiji',
                'officialName': 'Republic of Fiji',
                'region': 'Oceania',
                'subRegion': 'Melanesia',
                'iso2': 'FJ',
                'iso3': 'FJI',
            },
            {
                'commonName': 'Falkland Islands',
                'officialName': 'Falkland Islands',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'FK',
                'iso3': 'FLK',
            },
            {
                'commonName': 'France',
                'officialName': 'French Republic',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'FR',
                'iso3': 'FRA',
            },
            {
                'commonName': 'Faroe Islands',
                'officialName': 'Faroe Islands',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'FO',
                'iso3': 'FRO',
            },
            {
                'commonName': 'Micronesia',
                'officialName': 'Federated States of Micronesia',
                'region': 'Oceania',
                'subRegion': 'Micronesia',
                'iso2': 'FM',
                'iso3': 'FSM',
            },
            {
                'commonName': 'Gabon',
                'officialName': 'Gabonese Republic',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'GA',
                'iso3': 'GAB',
            },
            {
                'commonName': 'United Kingdom',
                'officialName': 'United Kingdom of Great Britain and Northern Ireland',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'GB',
                'iso3': 'GBR',
            },
            {
                'commonName': 'Georgia',
                'officialName': 'Georgia',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'GE',
                'iso3': 'GEO',
            },
            {
                'commonName': 'Guernsey',
                'officialName': 'Bailiwick of Guernsey',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'GG',
                'iso3': 'GGY',
            },
            {
                'commonName': 'Ghana',
                'officialName': 'Republic of Ghana',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'GH',
                'iso3': 'GHA',
            },
            {
                'commonName': 'Gibraltar',
                'officialName': 'Gibraltar',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'GI',
                'iso3': 'GIB',
            },
            {
                'commonName': 'Guinea',
                'officialName': 'Republic of Guinea',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'GN',
                'iso3': 'GIN',
            },
            {
                'commonName': 'Guadeloupe',
                'officialName': 'Guadeloupe',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'GP',
                'iso3': 'GLP',
            },
            {
                'commonName': 'Gambia',
                'officialName': 'Republic of the Gambia',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'GM',
                'iso3': 'GMB',
            },
            {
                'commonName': 'Guinea-Bissau',
                'officialName': 'Republic of Guinea-Bissau',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'GW',
                'iso3': 'GNB',
            },
            {
                'commonName': 'Equatorial Guinea',
                'officialName': 'Republic of Equatorial Guinea',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'GQ',
                'iso3': 'GNQ',
            },
            {
                'commonName': 'Greece',
                'officialName': 'Hellenic Republic',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'GR',
                'iso3': 'GRC',
            },
            {
                'commonName': 'Grenada',
                'officialName': 'Grenada',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'GD',
                'iso3': 'GRD',
            },
            {
                'commonName': 'Greenland',
                'officialName': 'Greenland',
                'region': 'Americas',
                'subRegion': 'Northern America',
                'iso2': 'GL',
                'iso3': 'GRL',
            },
            {
                'commonName': 'Guatemala',
                'officialName': 'Republic of Guatemala',
                'region': 'Americas',
                'subRegion': 'Central America',
                'iso2': 'GT',
                'iso3': 'GTM',
            },
            {
                'commonName': 'French Guiana',
                'officialName': 'Guiana',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'GF',
                'iso3': 'GUF',
            },
            {
                'commonName': 'Guam',
                'officialName': 'Guam',
                'region': 'Oceania',
                'subRegion': 'Micronesia',
                'iso2': 'GU',
                'iso3': 'GUM',
            },
            {
                'commonName': 'Guyana',
                'officialName': 'Co-operative Republic of Guyana',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'GY',
                'iso3': 'GUY',
            },
            {
                'commonName': 'Hong Kong',
                'officialName': 'Hong Kong Special Administrative Region of the People&#039;s Republic of China',
                'region': 'Asia',
                'subRegion': 'Eastern Asia',
                'iso2': 'HK',
                'iso3': 'HKG',
            },
            {
                'commonName': 'Heard Island and McDonald Islands',
                'officialName': 'Heard Island and McDonald Islands',
                'region': '',
                'subRegion': '',
                'iso2': 'HM',
                'iso3': 'HMD',
            },
            {
                'commonName': 'Honduras',
                'officialName': 'Republic of Honduras',
                'region': 'Americas',
                'subRegion': 'Central America',
                'iso2': 'HN',
                'iso3': 'HND',
            },
            {
                'commonName': 'Croatia',
                'officialName': 'Republic of Croatia',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'HR',
                'iso3': 'HRV',
            },
            {
                'commonName': 'Haiti',
                'officialName': 'Republic of Haiti',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'HT',
                'iso3': 'HTI',
            },
            {
                'commonName': 'Hungary',
                'officialName': 'Hungary',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'HU',
                'iso3': 'HUN',
            },
            {
                'commonName': 'Indonesia',
                'officialName': 'Republic of Indonesia',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'ID',
                'iso3': 'IDN',
            },
            {
                'commonName': 'Isle of Man',
                'officialName': 'Isle of Man',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'IM',
                'iso3': 'IMN',
            },
            {
                'commonName': 'India',
                'officialName': 'Republic of India',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'IN',
                'iso3': 'IND',
            },
            {
                'commonName': 'British Indian Ocean Territory',
                'officialName': 'British Indian Ocean Territory',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'IO',
                'iso3': 'IOT',
            },
            {
                'commonName': 'Ireland',
                'officialName': 'Republic of Ireland',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'IE',
                'iso3': 'IRL',
            },
            {
                'commonName': 'Iran',
                'officialName': 'Islamic Republic of Iran',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'IR',
                'iso3': 'IRN',
            },
            {
                'commonName': 'Iraq',
                'officialName': 'Republic of Iraq',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'IQ',
                'iso3': 'IRQ',
            },
            {
                'commonName': 'Iceland',
                'officialName': 'Iceland',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'IS',
                'iso3': 'ISL',
            },
            {
                'commonName': 'Israel',
                'officialName': 'State of Israel',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'IL',
                'iso3': 'ISR',
            },
            {
                'commonName': 'Italy',
                'officialName': 'Italian Republic',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'IT',
                'iso3': 'ITA',
            },
            {
                'commonName': 'Jamaica',
                'officialName': 'Jamaica',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'JM',
                'iso3': 'JAM',
            },
            {
                'commonName': 'Jersey',
                'officialName': 'Bailiwick of Jersey',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'JE',
                'iso3': 'JEY',
            },
            {
                'commonName': 'Jordan',
                'officialName': 'Hashemite Kingdom of Jordan',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'JO',
                'iso3': 'JOR',
            },
            {
                'commonName': 'Japan',
                'officialName': 'Japan',
                'region': 'Asia',
                'subRegion': 'Eastern Asia',
                'iso2': 'JP',
                'iso3': 'JPN',
            },
            {
                'commonName': 'Kazakhstan',
                'officialName': 'Republic of Kazakhstan',
                'region': 'Asia',
                'subRegion': 'Central Asia',
                'iso2': 'KZ',
                'iso3': 'KAZ',
            },
            {
                'commonName': 'Kenya',
                'officialName': 'Republic of Kenya',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'KE',
                'iso3': 'KEN',
            },
            {
                'commonName': 'Kyrgyzstan',
                'officialName': 'Kyrgyz Republic',
                'region': 'Asia',
                'subRegion': 'Central Asia',
                'iso2': 'KG',
                'iso3': 'KGZ',
            },
            {
                'commonName': 'Cambodia',
                'officialName': 'Kingdom of Cambodia',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'KH',
                'iso3': 'KHM',
            },
            {
                'commonName': 'Kiribati',
                'officialName': 'Independent and Sovereign Republic of Kiribati',
                'region': 'Oceania',
                'subRegion': 'Micronesia',
                'iso2': 'KI',
                'iso3': 'KIR',
            },
            {
                'commonName': 'Saint Kitts and Nevis',
                'officialName': 'Federation of Saint Christopher and Nevisa',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'KN',
                'iso3': 'KNA',
            },
            {
                'commonName': 'South Korea',
                'officialName': 'Republic of Korea',
                'region': 'Asia',
                'subRegion': 'Eastern Asia',
                'iso2': 'KR',
                'iso3': 'KOR',
            },
            {
                'commonName': 'Kosovo',
                'officialName': 'Republic of Kosovo',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'XK',
                'iso3': 'UNK',
            },
            {
                'commonName': 'Kuwait',
                'officialName': 'State of Kuwait',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'KW',
                'iso3': 'KWT',
            },
            {
                'commonName': 'Laos',
                'officialName': 'Lao People&#039;s Democratic Republic',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'LA',
                'iso3': 'LAO',
            },
            {
                'commonName': 'Lebanon',
                'officialName': 'Lebanese Republic',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'LB',
                'iso3': 'LBN',
            },
            {
                'commonName': 'Liberia',
                'officialName': 'Republic of Liberia',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'LR',
                'iso3': 'LBR',
            },
            {
                'commonName': 'Libya',
                'officialName': 'State of Libya',
                'region': 'Africa',
                'subRegion': 'Northern Africa',
                'iso2': 'LY',
                'iso3': 'LBY',
            },
            {
                'commonName': 'Saint Lucia',
                'officialName': 'Saint Lucia',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'LC',
                'iso3': 'LCA',
            },
            {
                'commonName': 'Liechtenstein',
                'officialName': 'Principality of Liechtenstein',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'LI',
                'iso3': 'LIE',
            },
            {
                'commonName': 'Sri Lanka',
                'officialName': 'Democratic Socialist Republic of Sri Lanka',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'LK',
                'iso3': 'LKA',
            },
            {
                'commonName': 'Lesotho',
                'officialName': 'Kingdom of Lesotho',
                'region': 'Africa',
                'subRegion': 'Southern Africa',
                'iso2': 'LS',
                'iso3': 'LSO',
            },
            {
                'commonName': 'Lithuania',
                'officialName': 'Republic of Lithuania',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'LT',
                'iso3': 'LTU',
            },
            {
                'commonName': 'Luxembourg',
                'officialName': 'Grand Duchy of Luxembourg',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'LU',
                'iso3': 'LUX',
            },
            {
                'commonName': 'Latvia',
                'officialName': 'Republic of Latvia',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'LV',
                'iso3': 'LVA',
            },
            {
                'commonName': 'Macau',
                'officialName': 'Macao Special Administrative Region of the People&#039;s Republic of China',
                'region': 'Asia',
                'subRegion': 'Eastern Asia',
                'iso2': 'MO',
                'iso3': 'MAC',
            },
            {
                'commonName': 'Saint Martin',
                'officialName': 'Saint Martin',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'MF',
                'iso3': 'MAF',
            },
            {
                'commonName': 'Morocco',
                'officialName': 'Kingdom of Morocco',
                'region': 'Africa',
                'subRegion': 'Northern Africa',
                'iso2': 'MA',
                'iso3': 'MAR',
            },
            {
                'commonName': 'Monaco',
                'officialName': 'Principality of Monaco',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'MC',
                'iso3': 'MCO',
            },
            {
                'commonName': 'Moldova',
                'officialName': 'Republic of Moldova',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'MD',
                'iso3': 'MDA',
            },
            {
                'commonName': 'Madagascar',
                'officialName': 'Republic of Madagascar',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'MG',
                'iso3': 'MDG',
            },
            {
                'commonName': 'Maldives',
                'officialName': 'Republic of the Maldives',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'MV',
                'iso3': 'MDV',
            },
            {
                'commonName': 'Mexico',
                'officialName': 'United Mexican States',
                'region': 'Americas',
                'subRegion': 'Northern America',
                'iso2': 'MX',
                'iso3': 'MEX',
            },
            {
                'commonName': 'Marshall Islands',
                'officialName': 'Republic of the Marshall Islands',
                'region': 'Oceania',
                'subRegion': 'Micronesia',
                'iso2': 'MH',
                'iso3': 'MHL',
            },
            {
                'commonName': 'Macedonia',
                'officialName': 'Republic of Macedonia',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'MK',
                'iso3': 'MKD',
            },
            {
                'commonName': 'Mali',
                'officialName': 'Republic of Mali',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'ML',
                'iso3': 'MLI',
            },
            {
                'commonName': 'Malta',
                'officialName': 'Republic of Malta',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'MT',
                'iso3': 'MLT',
            },
            {
                'commonName': 'Myanmar',
                'officialName': 'Republic of the Union of Myanmar',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'MM',
                'iso3': 'MMR',
            },
            {
                'commonName': 'Montenegro',
                'officialName': 'Montenegro',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'ME',
                'iso3': 'MNE',
            },
            {
                'commonName': 'Mongolia',
                'officialName': 'Mongolia',
                'region': 'Asia',
                'subRegion': 'Eastern Asia',
                'iso2': 'MN',
                'iso3': 'MNG',
            },
            {
                'commonName': 'Northern Mariana Islands',
                'officialName': 'Commonwealth of the Northern Mariana Islands',
                'region': 'Oceania',
                'subRegion': 'Micronesia',
                'iso2': 'MP',
                'iso3': 'MNP',
            },
            {
                'commonName': 'Mozambique',
                'officialName': 'Republic of Mozambique',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'MZ',
                'iso3': 'MOZ',
            },
            {
                'commonName': 'Mauritania',
                'officialName': 'Islamic Republic of Mauritania',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'MR',
                'iso3': 'MRT',
            },
            {
                'commonName': 'Montserrat',
                'officialName': 'Montserrat',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'MS',
                'iso3': 'MSR',
            },
            {
                'commonName': 'Martinique',
                'officialName': 'Martinique',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'MQ',
                'iso3': 'MTQ',
            },
            {
                'commonName': 'Mauritius',
                'officialName': 'Republic of Mauritius',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'MU',
                'iso3': 'MUS',
            },
            {
                'commonName': 'Malawi',
                'officialName': 'Republic of Malawi',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'MW',
                'iso3': 'MWI',
            },
            {
                'commonName': 'Malaysia',
                'officialName': 'Malaysia',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'MY',
                'iso3': 'MYS',
            },
            {
                'commonName': 'Mayotte',
                'officialName': 'Department of Mayotte',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'YT',
                'iso3': 'MYT',
            },
            {
                'commonName': 'Namibia',
                'officialName': 'Republic of Namibia',
                'region': 'Africa',
                'subRegion': 'Southern Africa',
                'iso2': 'NA',
                'iso3': 'NAM',
            },
            {
                'commonName': 'New Caledonia',
                'officialName': 'New Caledonia',
                'region': 'Oceania',
                'subRegion': 'Melanesia',
                'iso2': 'NC',
                'iso3': 'NCL',
            },
            {
                'commonName': 'Niger',
                'officialName': 'Republic of Niger',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'NE',
                'iso3': 'NER',
            },
            {
                'commonName': 'Norfolk Island',
                'officialName': 'Territory of Norfolk Island',
                'region': 'Oceania',
                'subRegion': 'Australia and New Zealand',
                'iso2': 'NF',
                'iso3': 'NFK',
            },
            {
                'commonName': 'Nigeria',
                'officialName': 'Federal Republic of Nigeria',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'NG',
                'iso3': 'NGA',
            },
            {
                'commonName': 'Nicaragua',
                'officialName': 'Republic of Nicaragua',
                'region': 'Americas',
                'subRegion': 'Central America',
                'iso2': 'NI',
                'iso3': 'NIC',
            },
            {
                'commonName': 'Niue',
                'officialName': 'Niue',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'NU',
                'iso3': 'NIU',
            },
            {
                'commonName': 'Netherlands',
                'officialName': 'Netherlands',
                'region': 'Europe',
                'subRegion': 'Western Europe',
                'iso2': 'NL',
                'iso3': 'NLD',
            },
            {
                'commonName': 'Norway',
                'officialName': 'Kingdom of Norway',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'NO',
                'iso3': 'NOR',
            },
            {
                'commonName': 'Nepal',
                'officialName': 'Federal Democratic Republic of Nepal',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'NP',
                'iso3': 'NPL',
            },
            {
                'commonName': 'Nauru',
                'officialName': 'Republic of Nauru',
                'region': 'Oceania',
                'subRegion': 'Micronesia',
                'iso2': 'NR',
                'iso3': 'NRU',
            },
            {
                'commonName': 'New Zealand',
                'officialName': 'New Zealand',
                'region': 'Oceania',
                'subRegion': 'Australia and New Zealand',
                'iso2': 'NZ',
                'iso3': 'NZL',
            },
            {
                'commonName': 'Oman',
                'officialName': 'Sultanate of Oman',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'OM',
                'iso3': 'OMN',
            },
            {
                'commonName': 'Pakistan',
                'officialName': 'Islamic Republic of Pakistan',
                'region': 'Asia',
                'subRegion': 'Southern Asia',
                'iso2': 'PK',
                'iso3': 'PAK',
            },
            {
                'commonName': 'Panama',
                'officialName': 'Republic of Panama',
                'region': 'Americas',
                'subRegion': 'Central America',
                'iso2': 'PA',
                'iso3': 'PAN',
            },
            {
                'commonName': 'Pitcairn Islands',
                'officialName': 'Pitcairn Group of Islands',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'PN',
                'iso3': 'PCN',
            },
            {
                'commonName': 'Peru',
                'officialName': 'Republic of Peru',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'PE',
                'iso3': 'PER',
            },
            {
                'commonName': 'Philippines',
                'officialName': 'Republic of the Philippines',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'PH',
                'iso3': 'PHL',
            },
            {
                'commonName': 'Palau',
                'officialName': 'Republic of Palau',
                'region': 'Oceania',
                'subRegion': 'Micronesia',
                'iso2': 'PW',
                'iso3': 'PLW',
            },
            {
                'commonName': 'Papua New Guinea',
                'officialName': 'Independent State of Papua New Guinea',
                'region': 'Oceania',
                'subRegion': 'Melanesia',
                'iso2': 'PG',
                'iso3': 'PNG',
            },
            {
                'commonName': 'Poland',
                'officialName': 'Republic of Poland',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'PL',
                'iso3': 'POL',
            },
            {
                'commonName': 'Puerto Rico',
                'officialName': 'Commonwealth of Puerto Rico',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'PR',
                'iso3': 'PRI',
            },
            {
                'commonName': 'North Korea',
                'officialName': 'Democratic People&#039;s Republic of Korea',
                'region': 'Asia',
                'subRegion': 'Eastern Asia',
                'iso2': 'KP',
                'iso3': 'PRK',
            },
            {
                'commonName': 'Portugal',
                'officialName': 'Portuguese Republic',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'PT',
                'iso3': 'PRT',
            },
            {
                'commonName': 'Paraguay',
                'officialName': 'Republic of Paraguay',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'PY',
                'iso3': 'PRY',
            },
            {
                'commonName': 'Palestine',
                'officialName': 'State of Palestine',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'PS',
                'iso3': 'PSE',
            },
            {
                'commonName': 'French Polynesia',
                'officialName': 'French Polynesia',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'PF',
                'iso3': 'PYF',
            },
            {
                'commonName': 'Qatar',
                'officialName': 'State of Qatar',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'QA',
                'iso3': 'QAT',
            },
            {
                'commonName': 'Réunion',
                'officialName': 'Réunion Island',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'RE',
                'iso3': 'REU',
            },
            {
                'commonName': 'Romania',
                'officialName': 'Romania',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'RO',
                'iso3': 'ROU',
            },
            {
                'commonName': 'Russia',
                'officialName': 'Russian Federation',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'RU',
                'iso3': 'RUS',
            },
            {
                'commonName': 'Rwanda',
                'officialName': 'Republic of Rwanda',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'RW',
                'iso3': 'RWA',
            },
            {
                'commonName': 'Saudi Arabia',
                'officialName': 'Kingdom of Saudi Arabia',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'SA',
                'iso3': 'SAU',
            },
            {
                'commonName': 'Sudan',
                'officialName': 'Republic of the Sudan',
                'region': 'Africa',
                'subRegion': 'Northern Africa',
                'iso2': 'SD',
                'iso3': 'SDN',
            },
            {
                'commonName': 'Senegal',
                'officialName': 'Republic of Senegal',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'SN',
                'iso3': 'SEN',
            },
            {
                'commonName': 'Singapore',
                'officialName': 'Republic of Singapore',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'SG',
                'iso3': 'SGP',
            },
            {
                'commonName': 'South Georgia',
                'officialName': 'South Georgia and the South Sandwich Islands',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'GS',
                'iso3': 'SGS',
            },
            {
                'commonName': 'Svalbard and Jan Mayen',
                'officialName': 'Svalbard og Jan Mayen',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'SJ',
                'iso3': 'SJM',
            },
            {
                'commonName': 'Solomon Islands',
                'officialName': 'Solomon Islands',
                'region': 'Oceania',
                'subRegion': 'Melanesia',
                'iso2': 'SB',
                'iso3': 'SLB',
            },
            {
                'commonName': 'Sierra Leone',
                'officialName': 'Republic of Sierra Leone',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'SL',
                'iso3': 'SLE',
            },
            {
                'commonName': 'El Salvador',
                'officialName': 'Republic of El Salvador',
                'region': 'Americas',
                'subRegion': 'Central America',
                'iso2': 'SV',
                'iso3': 'SLV',
            },
            {
                'commonName': 'San Marino',
                'officialName': 'Most Serene Republic of San Marino',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'SM',
                'iso3': 'SMR',
            },
            {
                'commonName': 'Somalia',
                'officialName': 'Federal Republic of Somalia',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'SO',
                'iso3': 'SOM',
            },
            {
                'commonName': 'Saint Pierre and Miquelon',
                'officialName': 'Saint Pierre and Miquelon',
                'region': 'Americas',
                'subRegion': 'Northern America',
                'iso2': 'PM',
                'iso3': 'SPM',
            },
            {
                'commonName': 'Serbia',
                'officialName': 'Republic of Serbia',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'RS',
                'iso3': 'SRB',
            },
            {
                'commonName': 'South Sudan',
                'officialName': 'Republic of South Sudan',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'SS',
                'iso3': 'SSD',
            },
            {
                'commonName': 'São Tomé and Príncipe',
                'officialName': 'Democratic Republic of São Tomé and Príncipe',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'ST',
                'iso3': 'STP',
            },
            {
                'commonName': 'Suriname',
                'officialName': 'Republic of Suriname',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'SR',
                'iso3': 'SUR',
            },
            {
                'commonName': 'Slovakia',
                'officialName': 'Slovak Republic',
                'region': 'Europe',
                'subRegion': 'Central Europe',
                'iso2': 'SK',
                'iso3': 'SVK',
            },
            {
                'commonName': 'Slovenia',
                'officialName': 'Republic of Slovenia',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'SI',
                'iso3': 'SVN',
            },
            {
                'commonName': 'Sweden',
                'officialName': 'Kingdom of Sweden',
                'region': 'Europe',
                'subRegion': 'Northern Europe',
                'iso2': 'SE',
                'iso3': 'SWE',
            },
            {
                'commonName': 'Swaziland',
                'officialName': 'Kingdom of Swaziland',
                'region': 'Africa',
                'subRegion': 'Southern Africa',
                'iso2': 'SZ',
                'iso3': 'SWZ',
            },
            {
                'commonName': 'Sint Maarten',
                'officialName': 'Sint Maarten',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'SX',
                'iso3': 'SXM',
            },
            {
                'commonName': 'Seychelles',
                'officialName': 'Republic of Seychelles',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'SC',
                'iso3': 'SYC',
            },
            {
                'commonName': 'Syria',
                'officialName': 'Syrian Arab Republic',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'SY',
                'iso3': 'SYR',
            },
            {
                'commonName': 'Turks and Caicos Islands',
                'officialName': 'Turks and Caicos Islands',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'TC',
                'iso3': 'TCA',
            },
            {
                'commonName': 'Chad',
                'officialName': 'Republic of Chad',
                'region': 'Africa',
                'subRegion': 'Middle Africa',
                'iso2': 'TD',
                'iso3': 'TCD',
            },
            {
                'commonName': 'Togo',
                'officialName': 'Togolese Republic',
                'region': 'Africa',
                'subRegion': 'Western Africa',
                'iso2': 'TG',
                'iso3': 'TGO',
            },
            {
                'commonName': 'Thailand',
                'officialName': 'Kingdom of Thailand',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'TH',
                'iso3': 'THA',
            },
            {
                'commonName': 'Tajikistan',
                'officialName': 'Republic of Tajikistan',
                'region': 'Asia',
                'subRegion': 'Central Asia',
                'iso2': 'TJ',
                'iso3': 'TJK',
            },
            {
                'commonName': 'Tokelau',
                'officialName': 'Tokelau',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'TK',
                'iso3': 'TKL',
            },
            {
                'commonName': 'Turkmenistan',
                'officialName': 'Turkmenistan',
                'region': 'Asia',
                'subRegion': 'Central Asia',
                'iso2': 'TM',
                'iso3': 'TKM',
            },
            {
                'commonName': 'Timor-Leste',
                'officialName': 'Democratic Republic of Timor-Leste',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'TL',
                'iso3': 'TLS',
            },
            {
                'commonName': 'Tonga',
                'officialName': 'Kingdom of Tonga',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'TO',
                'iso3': 'TON',
            },
            {
                'commonName': 'Trinidad and Tobago',
                'officialName': 'Republic of Trinidad and Tobago',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'TT',
                'iso3': 'TTO',
            },
            {
                'commonName': 'Tunisia',
                'officialName': 'Tunisian Republic',
                'region': 'Africa',
                'subRegion': 'Northern Africa',
                'iso2': 'TN',
                'iso3': 'TUN',
            },
            {
                'commonName': 'Turkey',
                'officialName': 'Republic of Turkey',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'TR',
                'iso3': 'TUR',
            },
            {
                'commonName': 'Tuvalu',
                'officialName': 'Tuvalu',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'TV',
                'iso3': 'TUV',
            },
            {
                'commonName': 'Taiwan',
                'officialName': 'Republic of China (Taiwan)',
                'region': 'Asia',
                'subRegion': 'Eastern Asia',
                'iso2': 'TW',
                'iso3': 'TWN',
            },
            {
                'commonName': 'Tanzania',
                'officialName': 'United Republic of Tanzania',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'TZ',
                'iso3': 'TZA',
            },
            {
                'commonName': 'Uganda',
                'officialName': 'Republic of Uganda',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'UG',
                'iso3': 'UGA',
            },
            {
                'commonName': 'Ukraine',
                'officialName': 'Ukraine',
                'region': 'Europe',
                'subRegion': 'Eastern Europe',
                'iso2': 'UA',
                'iso3': 'UKR',
            },
            {
                'commonName': 'United States Minor Outlying Islands',
                'officialName': 'United States Minor Outlying Islands',
                'region': 'Americas',
                'subRegion': 'Northern America',
                'iso2': 'UM',
                'iso3': 'UMI',
            },
            {
                'commonName': 'Uruguay',
                'officialName': 'Oriental Republic of Uruguay',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'UY',
                'iso3': 'URY',
            },
            {
                'commonName': 'United States',
                'officialName': 'United States of America',
                'region': 'Americas',
                'subRegion': 'Northern America',
                'iso2': 'US',
                'iso3': 'USA',
            },
            {
                'commonName': 'Uzbekistan',
                'officialName': 'Republic of Uzbekistan',
                'region': 'Asia',
                'subRegion': 'Central Asia',
                'iso2': 'UZ',
                'iso3': 'UZB',
            },
            {
                'commonName': 'Vatican City',
                'officialName': 'Vatican City State',
                'region': 'Europe',
                'subRegion': 'Southern Europe',
                'iso2': 'VA',
                'iso3': 'VAT',
            },
            {
                'commonName': 'Saint Vincent and the Grenadines',
                'officialName': 'Saint Vincent and the Grenadines',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'VC',
                'iso3': 'VCT',
            },
            {
                'commonName': 'Venezuela',
                'officialName': 'Bolivarian Republic of Venezuela',
                'region': 'Americas',
                'subRegion': 'South America',
                'iso2': 'VE',
                'iso3': 'VEN',
            },
            {
                'commonName': 'British Virgin Islands',
                'officialName': 'Virgin Islands',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'VG',
                'iso3': 'VGB',
            },
            {
                'commonName': 'United States Virgin Islands',
                'officialName': 'Virgin Islands of the United States',
                'region': 'Americas',
                'subRegion': 'Caribbean',
                'iso2': 'VI',
                'iso3': 'VIR',
            },
            {
                'commonName': 'Vietnam',
                'officialName': 'Socialist Republic of Vietnam',
                'region': 'Asia',
                'subRegion': 'South-Eastern Asia',
                'iso2': 'VN',
                'iso3': 'VNM',
            },
            {
                'commonName': 'Vanuatu',
                'officialName': 'Republic of Vanuatu',
                'region': 'Oceania',
                'subRegion': 'Melanesia',
                'iso2': 'VU',
                'iso3': 'VUT',
            },
            {
                'commonName': 'Wallis and Futuna',
                'officialName': 'Territory of the Wallis and Futuna Islands',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'WF',
                'iso3': 'WLF',
            },
            {
                'commonName': 'Samoa',
                'officialName': 'Independent State of Samoa',
                'region': 'Oceania',
                'subRegion': 'Polynesia',
                'iso2': 'WS',
                'iso3': 'WSM',
            },
            {
                'commonName': 'Yemen',
                'officialName': 'Republic of Yemen',
                'region': 'Asia',
                'subRegion': 'Western Asia',
                'iso2': 'YE',
                'iso3': 'YEM',
            },
            {
                'commonName': 'South Africa',
                'officialName': 'Republic of South Africa',
                'region': 'Africa',
                'subRegion': 'Southern Africa',
                'iso2': 'ZA',
                'iso3': 'ZAF',
            },
            {
                'commonName': 'Zambia',
                'officialName': 'Republic of Zambia',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'ZM',
                'iso3': 'ZMB',
            },
            {
                'commonName': 'Zimbabwe',
                'officialName': 'Republic of Zimbabwe',
                'region': 'Africa',
                'subRegion': 'Eastern Africa',
                'iso2': 'ZW',
                'iso3': 'ZWE',
            },
        ];
    }
}
