/**
 * This file was auto generated, please do not edit it directly.
 **/

export interface DateTimeZoneInterface {
  identifier: string;
  countryCode: string;
  latitude: string;
  longitude: string;
}

export class DateTimeZone {
  TimeZoneList(): DateTimeZoneInterface[] {
    return [
      {
        identifier: 'Africa/Abidjan',
        countryCode: 'CI',
        latitude: '5.31666',
        longitude: '-4.03334',
      },
      {
        identifier: 'Africa/Accra',
        countryCode: 'GH',
        latitude: '5.55',
        longitude: '-0.21666999999999',
      },
      {
        identifier: 'Africa/Addis_Ababa',
        countryCode: 'ET',
        latitude: '9.03333',
        longitude: '38.7',
      },
      {
        identifier: 'Africa/Algiers',
        countryCode: 'DZ',
        latitude: '36.78333',
        longitude: '3.05',
      },
      {
        identifier: 'Africa/Asmara',
        countryCode: 'ER',
        latitude: '15.33333',
        longitude: '38.88333',
      },
      {
        identifier: 'Africa/Bamako',
        countryCode: 'ML',
        latitude: '12.65',
        longitude: '-8',
      },
      {
        identifier: 'Africa/Bangui',
        countryCode: 'CF',
        latitude: '4.36666',
        longitude: '18.58333',
      },
      {
        identifier: 'Africa/Banjul',
        countryCode: 'GM',
        latitude: '13.46666',
        longitude: '-16.65',
      },
      {
        identifier: 'Africa/Bissau',
        countryCode: 'GW',
        latitude: '11.85',
        longitude: '-15.58334',
      },
      {
        identifier: 'Africa/Blantyre',
        countryCode: 'MW',
        latitude: '-15.78334',
        longitude: '35',
      },
      {
        identifier: 'Africa/Brazzaville',
        countryCode: 'CG',
        latitude: '-4.26667',
        longitude: '15.28333',
      },
      {
        identifier: 'Africa/Bujumbura',
        countryCode: 'BI',
        latitude: '-3.38334',
        longitude: '29.36666',
      },
      {
        identifier: 'Africa/Cairo',
        countryCode: 'EG',
        latitude: '30.05',
        longitude: '31.25',
      },
      {
        identifier: 'Africa/Casablanca',
        countryCode: 'MA',
        latitude: '33.65',
        longitude: '-7.58334',
      },
      {
        identifier: 'Africa/Ceuta',
        countryCode: 'ES',
        latitude: '35.88333',
        longitude: '-5.31667',
      },
      {
        identifier: 'Africa/Conakry',
        countryCode: 'GN',
        latitude: '9.51666',
        longitude: '-13.71667',
      },
      {
        identifier: 'Africa/Dakar',
        countryCode: 'SN',
        latitude: '14.66666',
        longitude: '-17.43334',
      },
      {
        identifier: 'Africa/Dar_es_Salaam',
        countryCode: 'TZ',
        latitude: '-6.8',
        longitude: '39.28333',
      },
      {
        identifier: 'Africa/Djibouti',
        countryCode: 'DJ',
        latitude: '11.6',
        longitude: '43.15',
      },
      {
        identifier: 'Africa/Douala',
        countryCode: 'CM',
        latitude: '4.05',
        longitude: '9.7',
      },
      {
        identifier: 'Africa/El_Aaiun',
        countryCode: 'EH',
        latitude: '27.15',
        longitude: '-13.2',
      },
      {
        identifier: 'Africa/Freetown',
        countryCode: 'SL',
        latitude: '8.5',
        longitude: '-13.25',
      },
      {
        identifier: 'Africa/Gaborone',
        countryCode: 'BW',
        latitude: '-24.65001',
        longitude: '25.91666',
      },
      {
        identifier: 'Africa/Harare',
        countryCode: 'ZW',
        latitude: '-17.83334',
        longitude: '31.05',
      },
      {
        identifier: 'Africa/Johannesburg',
        countryCode: 'ZA',
        latitude: '-26.25',
        longitude: '28',
      },
      {
        identifier: 'Africa/Juba',
        countryCode: 'SS',
        latitude: '4.85',
        longitude: '31.61666',
      },
      {
        identifier: 'Africa/Kampala',
        countryCode: 'UG',
        latitude: '0.31666',
        longitude: '32.41666',
      },
      {
        identifier: 'Africa/Khartoum',
        countryCode: 'SD',
        latitude: '15.6',
        longitude: '32.53333',
      },
      {
        identifier: 'Africa/Kigali',
        countryCode: 'RW',
        latitude: '-1.95',
        longitude: '30.06666',
      },
      {
        identifier: 'Africa/Kinshasa',
        countryCode: 'CD',
        latitude: '-4.3',
        longitude: '15.3',
      },
      {
        identifier: 'Africa/Lagos',
        countryCode: 'NG',
        latitude: '6.45',
        longitude: '3.4',
      },
      {
        identifier: 'Africa/Libreville',
        countryCode: 'GA',
        latitude: '0.38333',
        longitude: '9.45',
      },
      {
        identifier: 'Africa/Lome',
        countryCode: 'TG',
        latitude: '6.13333',
        longitude: '1.21666',
      },
      {
        identifier: 'Africa/Luanda',
        countryCode: 'AO',
        latitude: '-8.8',
        longitude: '13.23333',
      },
      {
        identifier: 'Africa/Lubumbashi',
        countryCode: 'CD',
        latitude: '-11.66667',
        longitude: '27.46666',
      },
      {
        identifier: 'Africa/Lusaka',
        countryCode: 'ZM',
        latitude: '-15.41667',
        longitude: '28.28333',
      },
      {
        identifier: 'Africa/Malabo',
        countryCode: 'GQ',
        latitude: '3.75',
        longitude: '8.78333',
      },
      {
        identifier: 'Africa/Maputo',
        countryCode: 'MZ',
        latitude: '-25.96667',
        longitude: '32.58333',
      },
      {
        identifier: 'Africa/Maseru',
        countryCode: 'LS',
        latitude: '-29.46667',
        longitude: '27.5',
      },
      {
        identifier: 'Africa/Mbabane',
        countryCode: 'SZ',
        latitude: '-26.3',
        longitude: '31.1',
      },
      {
        identifier: 'Africa/Mogadishu',
        countryCode: 'SO',
        latitude: '2.06666',
        longitude: '45.36666',
      },
      {
        identifier: 'Africa/Monrovia',
        countryCode: 'LR',
        latitude: '6.3',
        longitude: '-10.78334',
      },
      {
        identifier: 'Africa/Nairobi',
        countryCode: 'KE',
        latitude: '-1.28334',
        longitude: '36.81666',
      },
      {
        identifier: 'Africa/Ndjamena',
        countryCode: 'TD',
        latitude: '12.11666',
        longitude: '15.05',
      },
      {
        identifier: 'Africa/Niamey',
        countryCode: 'NE',
        latitude: '13.51666',
        longitude: '2.11666',
      },
      {
        identifier: 'Africa/Nouakchott',
        countryCode: 'MR',
        latitude: '18.1',
        longitude: '-15.95',
      },
      {
        identifier: 'Africa/Ouagadougou',
        countryCode: 'BF',
        latitude: '12.36666',
        longitude: '-1.51667',
      },
      {
        identifier: 'Africa/Porto-Novo',
        countryCode: 'BJ',
        latitude: '6.48333',
        longitude: '2.61666',
      },
      {
        identifier: 'Africa/Sao_Tome',
        countryCode: 'ST',
        latitude: '0.33333',
        longitude: '6.73333',
      },
      {
        identifier: 'Africa/Tripoli',
        countryCode: 'LY',
        latitude: '32.9',
        longitude: '13.18333',
      },
      {
        identifier: 'Africa/Tunis',
        countryCode: 'TN',
        latitude: '36.8',
        longitude: '10.18333',
      },
      {
        identifier: 'Africa/Windhoek',
        countryCode: 'NA',
        latitude: '-22.56667',
        longitude: '17.1',
      },
      {
        identifier: 'America/Adak',
        countryCode: 'US',
        latitude: '51.88',
        longitude: '-176.65806',
      },
      {
        identifier: 'America/Anchorage',
        countryCode: 'US',
        latitude: '61.21805',
        longitude: '-149.90028',
      },
      {
        identifier: 'America/Anguilla',
        countryCode: 'AI',
        latitude: '18.2',
        longitude: '-63.06667',
      },
      {
        identifier: 'America/Antigua',
        countryCode: 'AG',
        latitude: '17.05',
        longitude: '-61.8',
      },
      {
        identifier: 'America/Araguaina',
        countryCode: 'BR',
        latitude: '-7.2',
        longitude: '-48.2',
      },
      {
        identifier: 'America/Argentina/Buenos_Aires',
        countryCode: 'AR',
        latitude: '-34.6',
        longitude: '-58.45',
      },
      {
        identifier: 'America/Argentina/Catamarca',
        countryCode: 'AR',
        latitude: '-28.46667',
        longitude: '-65.78334',
      },
      {
        identifier: 'America/Argentina/Cordoba',
        countryCode: 'AR',
        latitude: '-31.4',
        longitude: '-64.18334',
      },
      {
        identifier: 'America/Argentina/Jujuy',
        countryCode: 'AR',
        latitude: '-24.18334',
        longitude: '-65.3',
      },
      {
        identifier: 'America/Argentina/La_Rioja',
        countryCode: 'AR',
        latitude: '-29.43334',
        longitude: '-66.85',
      },
      {
        identifier: 'America/Argentina/Mendoza',
        countryCode: 'AR',
        latitude: '-32.88334',
        longitude: '-68.81667',
      },
      {
        identifier: 'America/Argentina/Rio_Gallegos',
        countryCode: 'AR',
        latitude: '-51.63334',
        longitude: '-69.21667',
      },
      {
        identifier: 'America/Argentina/Salta',
        countryCode: 'AR',
        latitude: '-24.78334',
        longitude: '-65.41667',
      },
      {
        identifier: 'America/Argentina/San_Juan',
        countryCode: 'AR',
        latitude: '-31.53334',
        longitude: '-68.51667',
      },
      {
        identifier: 'America/Argentina/San_Luis',
        countryCode: 'AR',
        latitude: '-33.31667',
        longitude: '-66.35',
      },
      {
        identifier: 'America/Argentina/Tucuman',
        countryCode: 'AR',
        latitude: '-26.81667',
        longitude: '-65.21667',
      },
      {
        identifier: 'America/Argentina/Ushuaia',
        countryCode: 'AR',
        latitude: '-54.8',
        longitude: '-68.3',
      },
      {
        identifier: 'America/Aruba',
        countryCode: 'AW',
        latitude: '12.5',
        longitude: '-69.96667',
      },
      {
        identifier: 'America/Asuncion',
        countryCode: 'PY',
        latitude: '-25.26667',
        longitude: '-57.66667',
      },
      {
        identifier: 'America/Atikokan',
        countryCode: 'CA',
        latitude: '48.75861',
        longitude: '-91.62167',
      },
      {
        identifier: 'America/Bahia',
        countryCode: 'BR',
        latitude: '-12.98334',
        longitude: '-38.51667',
      },
      {
        identifier: 'America/Bahia_Banderas',
        countryCode: 'MX',
        latitude: '20.8',
        longitude: '-105.25',
      },
      {
        identifier: 'America/Barbados',
        countryCode: 'BB',
        latitude: '13.1',
        longitude: '-59.61667',
      },
      {
        identifier: 'America/Belem',
        countryCode: 'BR',
        latitude: '-1.45',
        longitude: '-48.48334',
      },
      {
        identifier: 'America/Belize',
        countryCode: 'BZ',
        latitude: '17.5',
        longitude: '-88.2',
      },
      {
        identifier: 'America/Blanc-Sablon',
        countryCode: 'CA',
        latitude: '51.41666',
        longitude: '-57.11667',
      },
      {
        identifier: 'America/Boa_Vista',
        countryCode: 'BR',
        latitude: '2.81666',
        longitude: '-60.66667',
      },
      {
        identifier: 'America/Bogota',
        countryCode: 'CO',
        latitude: '4.6',
        longitude: '-74.08334',
      },
      {
        identifier: 'America/Boise',
        countryCode: 'US',
        latitude: '43.61361',
        longitude: '-116.2025',
      },
      {
        identifier: 'America/Cambridge_Bay',
        countryCode: 'CA',
        latitude: '69.11388',
        longitude: '-105.05278',
      },
      {
        identifier: 'America/Campo_Grande',
        countryCode: 'BR',
        latitude: '-20.45',
        longitude: '-54.61667',
      },
      {
        identifier: 'America/Cancun',
        countryCode: 'MX',
        latitude: '21.08333',
        longitude: '-86.76667',
      },
      {
        identifier: 'America/Caracas',
        countryCode: 'VE',
        latitude: '10.5',
        longitude: '-66.93334',
      },
      {
        identifier: 'America/Cayenne',
        countryCode: 'GF',
        latitude: '4.93333',
        longitude: '-52.33334',
      },
      {
        identifier: 'America/Cayman',
        countryCode: 'KY',
        latitude: '19.3',
        longitude: '-81.38334',
      },
      {
        identifier: 'America/Chicago',
        countryCode: 'US',
        latitude: '41.85',
        longitude: '-87.65',
      },
      {
        identifier: 'America/Chihuahua',
        countryCode: 'MX',
        latitude: '28.63333',
        longitude: '-106.08334',
      },
      {
        identifier: 'America/Costa_Rica',
        countryCode: 'CR',
        latitude: '9.93333',
        longitude: '-84.08334',
      },
      {
        identifier: 'America/Creston',
        countryCode: 'CA',
        latitude: '49.1',
        longitude: '-116.51667',
      },
      {
        identifier: 'America/Cuiaba',
        countryCode: 'BR',
        latitude: '-15.58334',
        longitude: '-56.08334',
      },
      {
        identifier: 'America/Curacao',
        countryCode: 'CW',
        latitude: '12.18333',
        longitude: '-69',
      },
      {
        identifier: 'America/Danmarkshavn',
        countryCode: 'GL',
        latitude: '76.76666',
        longitude: '-18.66667',
      },
      {
        identifier: 'America/Dawson',
        countryCode: 'CA',
        latitude: '64.06666',
        longitude: '-139.41667',
      },
      {
        identifier: 'America/Dawson_Creek',
        countryCode: 'CA',
        latitude: '59.76666',
        longitude: '-120.23334',
      },
      {
        identifier: 'America/Denver',
        countryCode: 'US',
        latitude: '39.73916',
        longitude: '-104.98417',
      },
      {
        identifier: 'America/Detroit',
        countryCode: 'US',
        latitude: '42.33138',
        longitude: '-83.04584',
      },
      {
        identifier: 'America/Dominica',
        countryCode: 'DM',
        latitude: '15.3',
        longitude: '-61.4',
      },
      {
        identifier: 'America/Edmonton',
        countryCode: 'CA',
        latitude: '53.55',
        longitude: '-113.46667',
      },
      {
        identifier: 'America/Eirunepe',
        countryCode: 'BR',
        latitude: '-6.66667',
        longitude: '-69.86667',
      },
      {
        identifier: 'America/El_Salvador',
        countryCode: 'SV',
        latitude: '13.7',
        longitude: '-89.2',
      },
      {
        identifier: 'America/Fort_Nelson',
        countryCode: 'CA',
        latitude: '58.8',
        longitude: '-122.7',
      },
      {
        identifier: 'America/Fortaleza',
        countryCode: 'BR',
        latitude: '-3.71667',
        longitude: '-38.5',
      },
      {
        identifier: 'America/Glace_Bay',
        countryCode: 'CA',
        latitude: '46.19999',
        longitude: '-59.95',
      },
      {
        identifier: 'America/Goose_Bay',
        countryCode: 'CA',
        latitude: '53.33333',
        longitude: '-60.41667',
      },
      {
        identifier: 'America/Grand_Turk',
        countryCode: 'TC',
        latitude: '21.46666',
        longitude: '-71.13334',
      },
      {
        identifier: 'America/Grenada',
        countryCode: 'GD',
        latitude: '12.05',
        longitude: '-61.75',
      },
      {
        identifier: 'America/Guadeloupe',
        countryCode: 'GP',
        latitude: '16.23333',
        longitude: '-61.53334',
      },
      {
        identifier: 'America/Guatemala',
        countryCode: 'GT',
        latitude: '14.63333',
        longitude: '-90.51667',
      },
      {
        identifier: 'America/Guayaquil',
        countryCode: 'EC',
        latitude: '-2.16667',
        longitude: '-79.83334',
      },
      {
        identifier: 'America/Guyana',
        countryCode: 'GY',
        latitude: '6.8',
        longitude: '-58.16667',
      },
      {
        identifier: 'America/Halifax',
        countryCode: 'CA',
        latitude: '44.65',
        longitude: '-63.6',
      },
      {
        identifier: 'America/Havana',
        countryCode: 'CU',
        latitude: '23.13333',
        longitude: '-82.36667',
      },
      {
        identifier: 'America/Hermosillo',
        countryCode: 'MX',
        latitude: '29.06666',
        longitude: '-110.96667',
      },
      {
        identifier: 'America/Indiana/Indianapolis',
        countryCode: 'US',
        latitude: '39.76833',
        longitude: '-86.15806',
      },
      {
        identifier: 'America/Indiana/Knox',
        countryCode: 'US',
        latitude: '41.29583',
        longitude: '-86.625',
      },
      {
        identifier: 'America/Indiana/Marengo',
        countryCode: 'US',
        latitude: '38.37555',
        longitude: '-86.34473',
      },
      {
        identifier: 'America/Indiana/Petersburg',
        countryCode: 'US',
        latitude: '38.49194',
        longitude: '-87.27862',
      },
      {
        identifier: 'America/Indiana/Tell_City',
        countryCode: 'US',
        latitude: '37.95305',
        longitude: '-86.76139',
      },
      {
        identifier: 'America/Indiana/Vevay',
        countryCode: 'US',
        latitude: '38.74777',
        longitude: '-85.06723',
      },
      {
        identifier: 'America/Indiana/Vincennes',
        countryCode: 'US',
        latitude: '38.67722',
        longitude: '-87.52862',
      },
      {
        identifier: 'America/Indiana/Winamac',
        countryCode: 'US',
        latitude: '41.05138',
        longitude: '-86.60306',
      },
      {
        identifier: 'America/Inuvik',
        countryCode: 'CA',
        latitude: '68.34972',
        longitude: '-133.71667',
      },
      {
        identifier: 'America/Iqaluit',
        countryCode: 'CA',
        latitude: '63.73333',
        longitude: '-68.46667',
      },
      {
        identifier: 'America/Jamaica',
        countryCode: 'JM',
        latitude: '17.96805',
        longitude: '-76.79334',
      },
      {
        identifier: 'America/Juneau',
        countryCode: 'US',
        latitude: '58.30194',
        longitude: '-134.41973',
      },
      {
        identifier: 'America/Kentucky/Louisville',
        countryCode: 'US',
        latitude: '38.25416',
        longitude: '-85.75945',
      },
      {
        identifier: 'America/Kentucky/Monticello',
        countryCode: 'US',
        latitude: '36.82972',
        longitude: '-84.84917',
      },
      {
        identifier: 'America/Kralendijk',
        countryCode: 'BQ',
        latitude: '12.15083',
        longitude: '-68.27667',
      },
      {
        identifier: 'America/La_Paz',
        countryCode: 'BO',
        latitude: '-16.5',
        longitude: '-68.15',
      },
      {
        identifier: 'America/Lima',
        countryCode: 'PE',
        latitude: '-12.05',
        longitude: '-77.05',
      },
      {
        identifier: 'America/Los_Angeles',
        countryCode: 'US',
        latitude: '34.05222',
        longitude: '-118.24278',
      },
      {
        identifier: 'America/Lower_Princes',
        countryCode: 'SX',
        latitude: '18.05138',
        longitude: '-63.04723',
      },
      {
        identifier: 'America/Maceio',
        countryCode: 'BR',
        latitude: '-9.66667',
        longitude: '-35.71667',
      },
      {
        identifier: 'America/Managua',
        countryCode: 'NI',
        latitude: '12.15',
        longitude: '-86.28334',
      },
      {
        identifier: 'America/Manaus',
        countryCode: 'BR',
        latitude: '-3.13334',
        longitude: '-60.01667',
      },
      {
        identifier: 'America/Marigot',
        countryCode: 'MF',
        latitude: '18.06666',
        longitude: '-63.08334',
      },
      {
        identifier: 'America/Martinique',
        countryCode: 'MQ',
        latitude: '14.6',
        longitude: '-61.08334',
      },
      {
        identifier: 'America/Matamoros',
        countryCode: 'MX',
        latitude: '25.83333',
        longitude: '-97.5',
      },
      {
        identifier: 'America/Mazatlan',
        countryCode: 'MX',
        latitude: '23.21666',
        longitude: '-106.41667',
      },
      {
        identifier: 'America/Menominee',
        countryCode: 'US',
        latitude: '45.10777',
        longitude: '-87.61417',
      },
      {
        identifier: 'America/Merida',
        countryCode: 'MX',
        latitude: '20.96666',
        longitude: '-89.61667',
      },
      {
        identifier: 'America/Metlakatla',
        countryCode: 'US',
        latitude: '55.12694',
        longitude: '-131.57639',
      },
      {
        identifier: 'America/Mexico_City',
        countryCode: 'MX',
        latitude: '19.4',
        longitude: '-99.15001',
      },
      {
        identifier: 'America/Miquelon',
        countryCode: 'PM',
        latitude: '47.05',
        longitude: '-56.33334',
      },
      {
        identifier: 'America/Moncton',
        countryCode: 'CA',
        latitude: '46.1',
        longitude: '-64.78334',
      },
      {
        identifier: 'America/Monterrey',
        countryCode: 'MX',
        latitude: '25.66666',
        longitude: '-100.31667',
      },
      {
        identifier: 'America/Montevideo',
        countryCode: 'UY',
        latitude: '-34.90917',
        longitude: '-56.2125',
      },
      {
        identifier: 'America/Montserrat',
        countryCode: 'MS',
        latitude: '16.71666',
        longitude: '-62.21667',
      },
      {
        identifier: 'America/Nassau',
        countryCode: 'BS',
        latitude: '25.08333',
        longitude: '-77.35',
      },
      {
        identifier: 'America/New_York',
        countryCode: 'US',
        latitude: '40.71416',
        longitude: '-74.00639',
      },
      {
        identifier: 'America/Nipigon',
        countryCode: 'CA',
        latitude: '49.01666',
        longitude: '-88.26667',
      },
      {
        identifier: 'America/Nome',
        countryCode: 'US',
        latitude: '64.50111',
        longitude: '-165.40639',
      },
      {
        identifier: 'America/Noronha',
        countryCode: 'BR',
        latitude: '-3.85',
        longitude: '-32.41667',
      },
      {
        identifier: 'America/North_Dakota/Beulah',
        countryCode: 'US',
        latitude: '47.26416',
        longitude: '-101.77778',
      },
      {
        identifier: 'America/North_Dakota/Center',
        countryCode: 'US',
        latitude: '47.11638',
        longitude: '-101.29917',
      },
      {
        identifier: 'America/North_Dakota/New_Salem',
        countryCode: 'US',
        latitude: '46.845',
        longitude: '-101.41084',
      },
      {
        identifier: 'America/Nuuk',
        countryCode: 'GL',
        latitude: '64.18333',
        longitude: '-51.73334',
      },
      {
        identifier: 'America/Ojinaga',
        countryCode: 'MX',
        latitude: '29.56666',
        longitude: '-104.41667',
      },
      {
        identifier: 'America/Panama',
        countryCode: 'PA',
        latitude: '8.96666',
        longitude: '-79.53334',
      },
      {
        identifier: 'America/Pangnirtung',
        countryCode: 'CA',
        latitude: '66.13333',
        longitude: '-65.73334',
      },
      {
        identifier: 'America/Paramaribo',
        countryCode: 'SR',
        latitude: '5.83333',
        longitude: '-55.16667',
      },
      {
        identifier: 'America/Phoenix',
        countryCode: 'US',
        latitude: '33.44833',
        longitude: '-112.07334',
      },
      {
        identifier: 'America/Port-au-Prince',
        countryCode: 'HT',
        latitude: '18.53333',
        longitude: '-72.33334',
      },
      {
        identifier: 'America/Port_of_Spain',
        countryCode: 'TT',
        latitude: '10.65',
        longitude: '-61.51667',
      },
      {
        identifier: 'America/Porto_Velho',
        countryCode: 'BR',
        latitude: '-8.76667',
        longitude: '-63.9',
      },
      {
        identifier: 'America/Puerto_Rico',
        countryCode: 'PR',
        latitude: '18.46833',
        longitude: '-66.10612',
      },
      {
        identifier: 'America/Punta_Arenas',
        countryCode: 'CL',
        latitude: '-53.15',
        longitude: '-70.91667',
      },
      {
        identifier: 'America/Rainy_River',
        countryCode: 'CA',
        latitude: '48.71666',
        longitude: '-94.56667',
      },
      {
        identifier: 'America/Rankin_Inlet',
        countryCode: 'CA',
        latitude: '62.81666',
        longitude: '-92.08306',
      },
      {
        identifier: 'America/Recife',
        countryCode: 'BR',
        latitude: '-8.05',
        longitude: '-34.9',
      },
      {
        identifier: 'America/Regina',
        countryCode: 'CA',
        latitude: '50.4',
        longitude: '-104.65001',
      },
      {
        identifier: 'America/Resolute',
        countryCode: 'CA',
        latitude: '74.69555',
        longitude: '-94.82917',
      },
      {
        identifier: 'America/Rio_Branco',
        countryCode: 'BR',
        latitude: '-9.96667',
        longitude: '-67.8',
      },
      {
        identifier: 'America/Santarem',
        countryCode: 'BR',
        latitude: '-2.43334',
        longitude: '-54.86667',
      },
      {
        identifier: 'America/Santiago',
        countryCode: 'CL',
        latitude: '-33.45',
        longitude: '-70.66667',
      },
      {
        identifier: 'America/Santo_Domingo',
        countryCode: 'DO',
        latitude: '18.46666',
        longitude: '-69.9',
      },
      {
        identifier: 'America/Sao_Paulo',
        countryCode: 'BR',
        latitude: '-23.53334',
        longitude: '-46.61667',
      },
      {
        identifier: 'America/Scoresbysund',
        countryCode: 'GL',
        latitude: '70.48333',
        longitude: '-21.96667',
      },
      {
        identifier: 'America/Sitka',
        countryCode: 'US',
        latitude: '57.17638',
        longitude: '-135.30195',
      },
      {
        identifier: 'America/St_Barthelemy',
        countryCode: 'BL',
        latitude: '17.88333',
        longitude: '-62.85',
      },
      {
        identifier: 'America/St_Johns',
        countryCode: 'CA',
        latitude: '47.56666',
        longitude: '-52.71667',
      },
      {
        identifier: 'America/St_Kitts',
        countryCode: 'KN',
        latitude: '17.3',
        longitude: '-62.71667',
      },
      {
        identifier: 'America/St_Lucia',
        countryCode: 'LC',
        latitude: '14.01666',
        longitude: '-61',
      },
      {
        identifier: 'America/St_Thomas',
        countryCode: 'VI',
        latitude: '18.35',
        longitude: '-64.93334',
      },
      {
        identifier: 'America/St_Vincent',
        countryCode: 'VC',
        latitude: '13.15',
        longitude: '-61.23334',
      },
      {
        identifier: 'America/Swift_Current',
        countryCode: 'CA',
        latitude: '50.28333',
        longitude: '-107.83334',
      },
      {
        identifier: 'America/Tegucigalpa',
        countryCode: 'HN',
        latitude: '14.1',
        longitude: '-87.21667',
      },
      {
        identifier: 'America/Thule',
        countryCode: 'GL',
        latitude: '76.56666',
        longitude: '-68.78334',
      },
      {
        identifier: 'America/Thunder_Bay',
        countryCode: 'CA',
        latitude: '48.38333',
        longitude: '-89.25',
      },
      {
        identifier: 'America/Tijuana',
        countryCode: 'MX',
        latitude: '32.53333',
        longitude: '-117.01667',
      },
      {
        identifier: 'America/Toronto',
        countryCode: 'CA',
        latitude: '43.65',
        longitude: '-79.38334',
      },
      {
        identifier: 'America/Tortola',
        countryCode: 'VG',
        latitude: '18.45',
        longitude: '-64.61667',
      },
      {
        identifier: 'America/Vancouver',
        countryCode: 'CA',
        latitude: '49.26666',
        longitude: '-123.11667',
      },
      {
        identifier: 'America/Whitehorse',
        countryCode: 'CA',
        latitude: '60.71666',
        longitude: '-135.05001',
      },
      {
        identifier: 'America/Winnipeg',
        countryCode: 'CA',
        latitude: '49.88333',
        longitude: '-97.15001',
      },
      {
        identifier: 'America/Yakutat',
        countryCode: 'US',
        latitude: '59.54694',
        longitude: '-139.72723',
      },
      {
        identifier: 'America/Yellowknife',
        countryCode: 'CA',
        latitude: '62.44999',
        longitude: '-114.35',
      },
      {
        identifier: 'Antarctica/Casey',
        countryCode: 'AQ',
        latitude: '-66.28334',
        longitude: '110.51666',
      },
      {
        identifier: 'Antarctica/Davis',
        countryCode: 'AQ',
        latitude: '-68.58334',
        longitude: '77.96666',
      },
      {
        identifier: 'Antarctica/DumontDUrville',
        countryCode: 'AQ',
        latitude: '-66.66667',
        longitude: '140.01666',
      },
      {
        identifier: 'Antarctica/Macquarie',
        countryCode: 'AU',
        latitude: '-54.5',
        longitude: '158.95',
      },
      {
        identifier: 'Antarctica/Mawson',
        countryCode: 'AQ',
        latitude: '-67.6',
        longitude: '62.88333',
      },
      {
        identifier: 'Antarctica/McMurdo',
        countryCode: 'AQ',
        latitude: '-77.83334',
        longitude: '166.6',
      },
      {
        identifier: 'Antarctica/Palmer',
        countryCode: 'AQ',
        latitude: '-64.8',
        longitude: '-64.1',
      },
      {
        identifier: 'Antarctica/Rothera',
        countryCode: 'AQ',
        latitude: '-67.56667',
        longitude: '-68.13334',
      },
      {
        identifier: 'Antarctica/Syowa',
        countryCode: 'AQ',
        latitude: '-69.00612',
        longitude: '39.59',
      },
      {
        identifier: 'Antarctica/Troll',
        countryCode: 'AQ',
        latitude: '-72.01139',
        longitude: '2.535',
      },
      {
        identifier: 'Antarctica/Vostok',
        countryCode: 'AQ',
        latitude: '-78.40001',
        longitude: '106.89999',
      },
      {
        identifier: 'Arctic/Longyearbyen',
        countryCode: 'SJ',
        latitude: '78',
        longitude: '16',
      },
      {
        identifier: 'Asia/Aden',
        countryCode: 'YE',
        latitude: '12.75',
        longitude: '45.2',
      },
      {
        identifier: 'Asia/Almaty',
        countryCode: 'KZ',
        latitude: '43.25',
        longitude: '76.95',
      },
      {
        identifier: 'Asia/Amman',
        countryCode: 'JO',
        latitude: '31.95',
        longitude: '35.93333',
      },
      {
        identifier: 'Asia/Anadyr',
        countryCode: 'RU',
        latitude: '64.75',
        longitude: '177.48333',
      },
      {
        identifier: 'Asia/Aqtau',
        countryCode: 'KZ',
        latitude: '44.51666',
        longitude: '50.26666',
      },
      {
        identifier: 'Asia/Aqtobe',
        countryCode: 'KZ',
        latitude: '50.28333',
        longitude: '57.16666',
      },
      {
        identifier: 'Asia/Ashgabat',
        countryCode: 'TM',
        latitude: '37.95',
        longitude: '58.38333',
      },
      {
        identifier: 'Asia/Atyrau',
        countryCode: 'KZ',
        latitude: '47.11666',
        longitude: '51.93333',
      },
      {
        identifier: 'Asia/Baghdad',
        countryCode: 'IQ',
        latitude: '33.35',
        longitude: '44.41666',
      },
      {
        identifier: 'Asia/Bahrain',
        countryCode: 'BH',
        latitude: '26.38333',
        longitude: '50.58333',
      },
      {
        identifier: 'Asia/Baku',
        countryCode: 'AZ',
        latitude: '40.38333',
        longitude: '49.85',
      },
      {
        identifier: 'Asia/Bangkok',
        countryCode: 'TH',
        latitude: '13.75',
        longitude: '100.51666',
      },
      {
        identifier: 'Asia/Barnaul',
        countryCode: 'RU',
        latitude: '53.36666',
        longitude: '83.75',
      },
      {
        identifier: 'Asia/Beirut',
        countryCode: 'LB',
        latitude: '33.88333',
        longitude: '35.5',
      },
      {
        identifier: 'Asia/Bishkek',
        countryCode: 'KG',
        latitude: '42.9',
        longitude: '74.6',
      },
      {
        identifier: 'Asia/Brunei',
        countryCode: 'BN',
        latitude: '4.93333',
        longitude: '114.91666',
      },
      {
        identifier: 'Asia/Chita',
        countryCode: 'RU',
        latitude: '52.05',
        longitude: '113.46666',
      },
      {
        identifier: 'Asia/Choibalsan',
        countryCode: 'MN',
        latitude: '48.06666',
        longitude: '114.5',
      },
      {
        identifier: 'Asia/Colombo',
        countryCode: 'LK',
        latitude: '6.93333',
        longitude: '79.85',
      },
      {
        identifier: 'Asia/Damascus',
        countryCode: 'SY',
        latitude: '33.5',
        longitude: '36.3',
      },
      {
        identifier: 'Asia/Dhaka',
        countryCode: 'BD',
        latitude: '23.71666',
        longitude: '90.41666',
      },
      {
        identifier: 'Asia/Dili',
        countryCode: 'TL',
        latitude: '-8.55',
        longitude: '125.58333',
      },
      {
        identifier: 'Asia/Dubai',
        countryCode: 'AE',
        latitude: '25.3',
        longitude: '55.3',
      },
      {
        identifier: 'Asia/Dushanbe',
        countryCode: 'TJ',
        latitude: '38.58333',
        longitude: '68.8',
      },
      {
        identifier: 'Asia/Famagusta',
        countryCode: 'CY',
        latitude: '35.11666',
        longitude: '33.95',
      },
      {
        identifier: 'Asia/Gaza',
        countryCode: 'PS',
        latitude: '31.5',
        longitude: '34.46666',
      },
      {
        identifier: 'Asia/Hebron',
        countryCode: 'PS',
        latitude: '31.53333',
        longitude: '35.095',
      },
      {
        identifier: 'Asia/Ho_Chi_Minh',
        countryCode: 'VN',
        latitude: '10.75',
        longitude: '106.66666',
      },
      {
        identifier: 'Asia/Hong_Kong',
        countryCode: 'HK',
        latitude: '22.28333',
        longitude: '114.14999',
      },
      {
        identifier: 'Asia/Hovd',
        countryCode: 'MN',
        latitude: '48.01666',
        longitude: '91.64999',
      },
      {
        identifier: 'Asia/Irkutsk',
        countryCode: 'RU',
        latitude: '52.26666',
        longitude: '104.33333',
      },
      {
        identifier: 'Asia/Jakarta',
        countryCode: 'ID',
        latitude: '-6.16667',
        longitude: '106.8',
      },
      {
        identifier: 'Asia/Jayapura',
        countryCode: 'ID',
        latitude: '-2.53334',
        longitude: '140.7',
      },
      {
        identifier: 'Asia/Jerusalem',
        countryCode: 'IL',
        latitude: '31.78055',
        longitude: '35.22388',
      },
      {
        identifier: 'Asia/Kabul',
        countryCode: 'AF',
        latitude: '34.51666',
        longitude: '69.2',
      },
      {
        identifier: 'Asia/Kamchatka',
        countryCode: 'RU',
        latitude: '53.01666',
        longitude: '158.65',
      },
      {
        identifier: 'Asia/Karachi',
        countryCode: 'PK',
        latitude: '24.86666',
        longitude: '67.05',
      },
      {
        identifier: 'Asia/Kathmandu',
        countryCode: 'NP',
        latitude: '27.71666',
        longitude: '85.31666',
      },
      {
        identifier: 'Asia/Khandyga',
        countryCode: 'RU',
        latitude: '62.65638',
        longitude: '135.55388',
      },
      {
        identifier: 'Asia/Kolkata',
        countryCode: 'IN',
        latitude: '22.53333',
        longitude: '88.36666',
      },
      {
        identifier: 'Asia/Krasnoyarsk',
        countryCode: 'RU',
        latitude: '56.01666',
        longitude: '92.83333',
      },
      {
        identifier: 'Asia/Kuala_Lumpur',
        countryCode: 'MY',
        latitude: '3.16666',
        longitude: '101.7',
      },
      {
        identifier: 'Asia/Kuching',
        countryCode: 'MY',
        latitude: '1.55',
        longitude: '110.33333',
      },
      {
        identifier: 'Asia/Kuwait',
        countryCode: 'KW',
        latitude: '29.33333',
        longitude: '47.98333',
      },
      {
        identifier: 'Asia/Macau',
        countryCode: 'MO',
        latitude: '22.19722',
        longitude: '113.54166',
      },
      {
        identifier: 'Asia/Magadan',
        countryCode: 'RU',
        latitude: '59.56666',
        longitude: '150.8',
      },
      {
        identifier: 'Asia/Makassar',
        countryCode: 'ID',
        latitude: '-5.11667',
        longitude: '119.39999',
      },
      {
        identifier: 'Asia/Manila',
        countryCode: 'PH',
        latitude: '14.58333',
        longitude: '121',
      },
      {
        identifier: 'Asia/Muscat',
        countryCode: 'OM',
        latitude: '23.6',
        longitude: '58.58333',
      },
      {
        identifier: 'Asia/Nicosia',
        countryCode: 'CY',
        latitude: '35.16666',
        longitude: '33.36666',
      },
      {
        identifier: 'Asia/Novokuznetsk',
        countryCode: 'RU',
        latitude: '53.75',
        longitude: '87.11666',
      },
      {
        identifier: 'Asia/Novosibirsk',
        countryCode: 'RU',
        latitude: '55.03333',
        longitude: '82.91666',
      },
      {
        identifier: 'Asia/Omsk',
        countryCode: 'RU',
        latitude: '55',
        longitude: '73.4',
      },
      {
        identifier: 'Asia/Oral',
        countryCode: 'KZ',
        latitude: '51.21666',
        longitude: '51.35',
      },
      {
        identifier: 'Asia/Phnom_Penh',
        countryCode: 'KH',
        latitude: '11.55',
        longitude: '104.91666',
      },
      {
        identifier: 'Asia/Pontianak',
        countryCode: 'ID',
        latitude: '-0.033339999999995',
        longitude: '109.33333',
      },
      {
        identifier: 'Asia/Pyongyang',
        countryCode: 'KP',
        latitude: '39.01666',
        longitude: '125.75',
      },
      {
        identifier: 'Asia/Qatar',
        countryCode: 'QA',
        latitude: '25.28333',
        longitude: '51.53333',
      },
      {
        identifier: 'Asia/Qostanay',
        countryCode: 'KZ',
        latitude: '53.19999',
        longitude: '63.61666',
      },
      {
        identifier: 'Asia/Qyzylorda',
        countryCode: 'KZ',
        latitude: '44.8',
        longitude: '65.46666',
      },
      {
        identifier: 'Asia/Riyadh',
        countryCode: 'SA',
        latitude: '24.63333',
        longitude: '46.71666',
      },
      {
        identifier: 'Asia/Sakhalin',
        countryCode: 'RU',
        latitude: '46.96666',
        longitude: '142.7',
      },
      {
        identifier: 'Asia/Samarkand',
        countryCode: 'UZ',
        latitude: '39.66666',
        longitude: '66.8',
      },
      {
        identifier: 'Asia/Seoul',
        countryCode: 'KR',
        latitude: '37.55',
        longitude: '126.96666',
      },
      {
        identifier: 'Asia/Shanghai',
        countryCode: 'CN',
        latitude: '31.23333',
        longitude: '121.46666',
      },
      {
        identifier: 'Asia/Singapore',
        countryCode: 'SG',
        latitude: '1.28333',
        longitude: '103.85',
      },
      {
        identifier: 'Asia/Srednekolymsk',
        countryCode: 'RU',
        latitude: '67.46666',
        longitude: '153.71666',
      },
      {
        identifier: 'Asia/Taipei',
        countryCode: 'TW',
        latitude: '25.05',
        longitude: '121.5',
      },
      {
        identifier: 'Asia/Tashkent',
        countryCode: 'UZ',
        latitude: '41.33333',
        longitude: '69.3',
      },
      {
        identifier: 'Asia/Tbilisi',
        countryCode: 'GE',
        latitude: '41.71666',
        longitude: '44.81666',
      },
      {
        identifier: 'Asia/Tehran',
        countryCode: 'IR',
        latitude: '35.66666',
        longitude: '51.43333',
      },
      {
        identifier: 'Asia/Thimphu',
        countryCode: 'BT',
        latitude: '27.46666',
        longitude: '89.64999',
      },
      {
        identifier: 'Asia/Tokyo',
        countryCode: 'JP',
        latitude: '35.65444',
        longitude: '139.74472',
      },
      {
        identifier: 'Asia/Tomsk',
        countryCode: 'RU',
        latitude: '56.5',
        longitude: '84.96666',
      },
      {
        identifier: 'Asia/Ulaanbaatar',
        countryCode: 'MN',
        latitude: '47.91666',
        longitude: '106.88333',
      },
      {
        identifier: 'Asia/Urumqi',
        countryCode: 'CN',
        latitude: '43.8',
        longitude: '87.58333',
      },
      {
        identifier: 'Asia/Ust-Nera',
        countryCode: 'RU',
        latitude: '64.56027',
        longitude: '143.22666',
      },
      {
        identifier: 'Asia/Vientiane',
        countryCode: 'LA',
        latitude: '17.96666',
        longitude: '102.6',
      },
      {
        identifier: 'Asia/Vladivostok',
        countryCode: 'RU',
        latitude: '43.16666',
        longitude: '131.93333',
      },
      {
        identifier: 'Asia/Yakutsk',
        countryCode: 'RU',
        latitude: '62',
        longitude: '129.66666',
      },
      {
        identifier: 'Asia/Yangon',
        countryCode: 'MM',
        latitude: '16.78333',
        longitude: '96.16666',
      },
      {
        identifier: 'Asia/Yekaterinburg',
        countryCode: 'RU',
        latitude: '56.85',
        longitude: '60.6',
      },
      {
        identifier: 'Asia/Yerevan',
        countryCode: 'AM',
        latitude: '40.18333',
        longitude: '44.5',
      },
      {
        identifier: 'Atlantic/Azores',
        countryCode: 'PT',
        latitude: '37.73333',
        longitude: '-25.66667',
      },
      {
        identifier: 'Atlantic/Bermuda',
        countryCode: 'BM',
        latitude: '32.28333',
        longitude: '-64.76667',
      },
      {
        identifier: 'Atlantic/Canary',
        countryCode: 'ES',
        latitude: '28.1',
        longitude: '-15.4',
      },
      {
        identifier: 'Atlantic/Cape_Verde',
        countryCode: 'CV',
        latitude: '14.91666',
        longitude: '-23.51667',
      },
      {
        identifier: 'Atlantic/Faroe',
        countryCode: 'FO',
        latitude: '62.01666',
        longitude: '-6.76667',
      },
      {
        identifier: 'Atlantic/Madeira',
        countryCode: 'PT',
        latitude: '32.63333',
        longitude: '-16.9',
      },
      {
        identifier: 'Atlantic/Reykjavik',
        countryCode: 'IS',
        latitude: '64.15',
        longitude: '-21.85',
      },
      {
        identifier: 'Atlantic/South_Georgia',
        countryCode: 'GS',
        latitude: '-54.26667',
        longitude: '-36.53334',
      },
      {
        identifier: 'Atlantic/St_Helena',
        countryCode: 'SH',
        latitude: '-15.91667',
        longitude: '-5.7',
      },
      {
        identifier: 'Atlantic/Stanley',
        countryCode: 'FK',
        latitude: '-51.70001',
        longitude: '-57.85',
      },
      {
        identifier: 'Australia/Adelaide',
        countryCode: 'AU',
        latitude: '-34.91667',
        longitude: '138.58333',
      },
      {
        identifier: 'Australia/Brisbane',
        countryCode: 'AU',
        latitude: '-27.46667',
        longitude: '153.03333',
      },
      {
        identifier: 'Australia/Broken_Hill',
        countryCode: 'AU',
        latitude: '-31.95',
        longitude: '141.45',
      },
      {
        identifier: 'Australia/Currie',
        countryCode: 'AU',
        latitude: '-39.93334',
        longitude: '143.86666',
      },
      {
        identifier: 'Australia/Darwin',
        countryCode: 'AU',
        latitude: '-12.46667',
        longitude: '130.83333',
      },
      {
        identifier: 'Australia/Eucla',
        countryCode: 'AU',
        latitude: '-31.71667',
        longitude: '128.86666',
      },
      {
        identifier: 'Australia/Hobart',
        countryCode: 'AU',
        latitude: '-42.88334',
        longitude: '147.31666',
      },
      {
        identifier: 'Australia/Lindeman',
        countryCode: 'AU',
        latitude: '-20.26667',
        longitude: '149',
      },
      {
        identifier: 'Australia/Lord_Howe',
        countryCode: 'AU',
        latitude: '-31.55',
        longitude: '159.08333',
      },
      {
        identifier: 'Australia/Melbourne',
        countryCode: 'AU',
        latitude: '-37.81667',
        longitude: '144.96666',
      },
      {
        identifier: 'Australia/Perth',
        countryCode: 'AU',
        latitude: '-31.95',
        longitude: '115.85',
      },
      {
        identifier: 'Australia/Sydney',
        countryCode: 'AU',
        latitude: '-33.86667',
        longitude: '151.21666',
      },
      {
        identifier: 'Europe/Amsterdam',
        countryCode: 'NL',
        latitude: '52.36666',
        longitude: '4.9',
      },
      {
        identifier: 'Europe/Andorra',
        countryCode: 'AD',
        latitude: '42.5',
        longitude: '1.51666',
      },
      {
        identifier: 'Europe/Astrakhan',
        countryCode: 'RU',
        latitude: '46.35',
        longitude: '48.05',
      },
      {
        identifier: 'Europe/Athens',
        countryCode: 'GR',
        latitude: '37.96666',
        longitude: '23.71666',
      },
      {
        identifier: 'Europe/Belgrade',
        countryCode: 'RS',
        latitude: '44.83333',
        longitude: '20.5',
      },
      {
        identifier: 'Europe/Berlin',
        countryCode: 'DE',
        latitude: '52.5',
        longitude: '13.36666',
      },
      {
        identifier: 'Europe/Bratislava',
        countryCode: 'SK',
        latitude: '48.15',
        longitude: '17.11666',
      },
      {
        identifier: 'Europe/Brussels',
        countryCode: 'BE',
        latitude: '50.83333',
        longitude: '4.33333',
      },
      {
        identifier: 'Europe/Bucharest',
        countryCode: 'RO',
        latitude: '44.43333',
        longitude: '26.1',
      },
      {
        identifier: 'Europe/Budapest',
        countryCode: 'HU',
        latitude: '47.5',
        longitude: '19.08333',
      },
      {
        identifier: 'Europe/Busingen',
        countryCode: 'DE',
        latitude: '47.69999',
        longitude: '8.68333',
      },
      {
        identifier: 'Europe/Chisinau',
        countryCode: 'MD',
        latitude: '47',
        longitude: '28.83333',
      },
      {
        identifier: 'Europe/Copenhagen',
        countryCode: 'DK',
        latitude: '55.66666',
        longitude: '12.58333',
      },
      {
        identifier: 'Europe/Dublin',
        countryCode: 'IE',
        latitude: '53.33333',
        longitude: '-6.25',
      },
      {
        identifier: 'Europe/Gibraltar',
        countryCode: 'GI',
        latitude: '36.13333',
        longitude: '-5.35',
      },
      {
        identifier: 'Europe/Guernsey',
        countryCode: 'GG',
        latitude: '49.45472',
        longitude: '-2.53612',
      },
      {
        identifier: 'Europe/Helsinki',
        countryCode: 'FI',
        latitude: '60.16666',
        longitude: '24.96666',
      },
      {
        identifier: 'Europe/Isle_of_Man',
        countryCode: 'IM',
        latitude: '54.15',
        longitude: '-4.46667',
      },
      {
        identifier: 'Europe/Istanbul',
        countryCode: 'TR',
        latitude: '41.01666',
        longitude: '28.96666',
      },
      {
        identifier: 'Europe/Jersey',
        countryCode: 'JE',
        latitude: '49.18361',
        longitude: '-2.10667',
      },
      {
        identifier: 'Europe/Kaliningrad',
        countryCode: 'RU',
        latitude: '54.71666',
        longitude: '20.5',
      },
      {
        identifier: 'Europe/Kiev',
        countryCode: 'UA',
        latitude: '50.43333',
        longitude: '30.51666',
      },
      {
        identifier: 'Europe/Kirov',
        countryCode: 'RU',
        latitude: '58.6',
        longitude: '49.65',
      },
      {
        identifier: 'Europe/Lisbon',
        countryCode: 'PT',
        latitude: '38.71666',
        longitude: '-9.13334',
      },
      {
        identifier: 'Europe/Ljubljana',
        countryCode: 'SI',
        latitude: '46.05',
        longitude: '14.51666',
      },
      {
        identifier: 'Europe/London',
        countryCode: 'GB',
        latitude: '51.50833',
        longitude: '-0.12528',
      },
      {
        identifier: 'Europe/Luxembourg',
        countryCode: 'LU',
        latitude: '49.6',
        longitude: '6.15',
      },
      {
        identifier: 'Europe/Madrid',
        countryCode: 'ES',
        latitude: '40.4',
        longitude: '-3.68334',
      },
      {
        identifier: 'Europe/Malta',
        countryCode: 'MT',
        latitude: '35.9',
        longitude: '14.51666',
      },
      {
        identifier: 'Europe/Mariehamn',
        countryCode: 'AX',
        latitude: '60.1',
        longitude: '19.95',
      },
      {
        identifier: 'Europe/Minsk',
        countryCode: 'BY',
        latitude: '53.9',
        longitude: '27.56666',
      },
      {
        identifier: 'Europe/Monaco',
        countryCode: 'MC',
        latitude: '43.69999',
        longitude: '7.38333',
      },
      {
        identifier: 'Europe/Moscow',
        countryCode: 'RU',
        latitude: '55.75583',
        longitude: '37.61777',
      },
      {
        identifier: 'Europe/Oslo',
        countryCode: 'NO',
        latitude: '59.91666',
        longitude: '10.75',
      },
      {
        identifier: 'Europe/Paris',
        countryCode: 'FR',
        latitude: '48.86666',
        longitude: '2.33333',
      },
      {
        identifier: 'Europe/Podgorica',
        countryCode: 'ME',
        latitude: '42.43333',
        longitude: '19.26666',
      },
      {
        identifier: 'Europe/Prague',
        countryCode: 'CZ',
        latitude: '50.08333',
        longitude: '14.43333',
      },
      {
        identifier: 'Europe/Riga',
        countryCode: 'LV',
        latitude: '56.94999',
        longitude: '24.1',
      },
      {
        identifier: 'Europe/Rome',
        countryCode: 'IT',
        latitude: '41.9',
        longitude: '12.48333',
      },
      {
        identifier: 'Europe/Samara',
        countryCode: 'RU',
        latitude: '53.19999',
        longitude: '50.15',
      },
      {
        identifier: 'Europe/San_Marino',
        countryCode: 'SM',
        latitude: '43.91666',
        longitude: '12.46666',
      },
      {
        identifier: 'Europe/Sarajevo',
        countryCode: 'BA',
        latitude: '43.86666',
        longitude: '18.41666',
      },
      {
        identifier: 'Europe/Saratov',
        countryCode: 'RU',
        latitude: '51.56666',
        longitude: '46.03333',
      },
      {
        identifier: 'Europe/Simferopol',
        countryCode: 'UA',
        latitude: '44.94999',
        longitude: '34.1',
      },
      {
        identifier: 'Europe/Skopje',
        countryCode: 'MK',
        latitude: '41.98333',
        longitude: '21.43333',
      },
      {
        identifier: 'Europe/Sofia',
        countryCode: 'BG',
        latitude: '42.68333',
        longitude: '23.31666',
      },
      {
        identifier: 'Europe/Stockholm',
        countryCode: 'SE',
        latitude: '59.33333',
        longitude: '18.05',
      },
      {
        identifier: 'Europe/Tallinn',
        countryCode: 'EE',
        latitude: '59.41666',
        longitude: '24.75',
      },
      {
        identifier: 'Europe/Tirane',
        countryCode: 'AL',
        latitude: '41.33333',
        longitude: '19.83333',
      },
      {
        identifier: 'Europe/Ulyanovsk',
        countryCode: 'RU',
        latitude: '54.33333',
        longitude: '48.4',
      },
      {
        identifier: 'Europe/Uzhgorod',
        countryCode: 'UA',
        latitude: '48.61666',
        longitude: '22.3',
      },
      {
        identifier: 'Europe/Vaduz',
        countryCode: 'LI',
        latitude: '47.15',
        longitude: '9.51666',
      },
      {
        identifier: 'Europe/Vatican',
        countryCode: 'VA',
        latitude: '41.90222',
        longitude: '12.45305',
      },
      {
        identifier: 'Europe/Vienna',
        countryCode: 'AT',
        latitude: '48.21666',
        longitude: '16.33333',
      },
      {
        identifier: 'Europe/Vilnius',
        countryCode: 'LT',
        latitude: '54.68333',
        longitude: '25.31666',
      },
      {
        identifier: 'Europe/Volgograd',
        countryCode: 'RU',
        latitude: '48.73333',
        longitude: '44.41666',
      },
      {
        identifier: 'Europe/Warsaw',
        countryCode: 'PL',
        latitude: '52.25',
        longitude: '21',
      },
      {
        identifier: 'Europe/Zagreb',
        countryCode: 'HR',
        latitude: '45.8',
        longitude: '15.96666',
      },
      {
        identifier: 'Europe/Zaporozhye',
        countryCode: 'UA',
        latitude: '47.83333',
        longitude: '35.16666',
      },
      {
        identifier: 'Europe/Zurich',
        countryCode: 'CH',
        latitude: '47.38333',
        longitude: '8.53333',
      },
      {
        identifier: 'Indian/Antananarivo',
        countryCode: 'MG',
        latitude: '-18.91667',
        longitude: '47.51666',
      },
      {
        identifier: 'Indian/Chagos',
        countryCode: 'IO',
        latitude: '-7.33334',
        longitude: '72.41666',
      },
      {
        identifier: 'Indian/Christmas',
        countryCode: 'CX',
        latitude: '-10.41667',
        longitude: '105.71666',
      },
      {
        identifier: 'Indian/Cocos',
        countryCode: 'CC',
        latitude: '-12.16667',
        longitude: '96.91666',
      },
      {
        identifier: 'Indian/Comoro',
        countryCode: 'KM',
        latitude: '-11.68334',
        longitude: '43.26666',
      },
      {
        identifier: 'Indian/Kerguelen',
        countryCode: 'TF',
        latitude: '-49.35278',
        longitude: '70.2175',
      },
      {
        identifier: 'Indian/Mahe',
        countryCode: 'SC',
        latitude: '-4.66667',
        longitude: '55.46666',
      },
      {
        identifier: 'Indian/Maldives',
        countryCode: 'MV',
        latitude: '4.16666',
        longitude: '73.5',
      },
      {
        identifier: 'Indian/Mauritius',
        countryCode: 'MU',
        latitude: '-20.16667',
        longitude: '57.5',
      },
      {
        identifier: 'Indian/Mayotte',
        countryCode: 'YT',
        latitude: '-12.78334',
        longitude: '45.23333',
      },
      {
        identifier: 'Indian/Reunion',
        countryCode: 'RE',
        latitude: '-20.86667',
        longitude: '55.46666',
      },
      {
        identifier: 'Pacific/Apia',
        countryCode: 'WS',
        latitude: '-13.83334',
        longitude: '-171.73334',
      },
      {
        identifier: 'Pacific/Auckland',
        countryCode: 'NZ',
        latitude: '-36.86667',
        longitude: '174.76666',
      },
      {
        identifier: 'Pacific/Bougainville',
        countryCode: 'PG',
        latitude: '-6.21667',
        longitude: '155.56666',
      },
      {
        identifier: 'Pacific/Chatham',
        countryCode: 'NZ',
        latitude: '-43.95',
        longitude: '-176.55001',
      },
      {
        identifier: 'Pacific/Chuuk',
        countryCode: 'FM',
        latitude: '7.41666',
        longitude: '151.78333',
      },
      {
        identifier: 'Pacific/Easter',
        countryCode: 'CL',
        latitude: '-27.15',
        longitude: '-109.43334',
      },
      {
        identifier: 'Pacific/Efate',
        countryCode: 'VU',
        latitude: '-17.66667',
        longitude: '168.41666',
      },
      {
        identifier: 'Pacific/Enderbury',
        countryCode: 'KI',
        latitude: '-3.13334',
        longitude: '-171.08334',
      },
      {
        identifier: 'Pacific/Fakaofo',
        countryCode: 'TK',
        latitude: '-9.36667',
        longitude: '-171.23334',
      },
      {
        identifier: 'Pacific/Fiji',
        countryCode: 'FJ',
        latitude: '-18.13334',
        longitude: '178.41666',
      },
      {
        identifier: 'Pacific/Funafuti',
        countryCode: 'TV',
        latitude: '-8.51667',
        longitude: '179.21666',
      },
      {
        identifier: 'Pacific/Galapagos',
        countryCode: 'EC',
        latitude: '-0.90000000000001',
        longitude: '-89.6',
      },
      {
        identifier: 'Pacific/Gambier',
        countryCode: 'PF',
        latitude: '-23.13334',
        longitude: '-134.95',
      },
      {
        identifier: 'Pacific/Guadalcanal',
        countryCode: 'SB',
        latitude: '-9.53334',
        longitude: '160.2',
      },
      {
        identifier: 'Pacific/Guam',
        countryCode: 'GU',
        latitude: '13.46666',
        longitude: '144.75',
      },
      {
        identifier: 'Pacific/Honolulu',
        countryCode: 'US',
        latitude: '21.30694',
        longitude: '-157.85834',
      },
      {
        identifier: 'Pacific/Kiritimati',
        countryCode: 'KI',
        latitude: '1.86666',
        longitude: '-157.33334',
      },
      {
        identifier: 'Pacific/Kosrae',
        countryCode: 'FM',
        latitude: '5.31666',
        longitude: '162.98333',
      },
      {
        identifier: 'Pacific/Kwajalein',
        countryCode: 'MH',
        latitude: '9.08333',
        longitude: '167.33333',
      },
      {
        identifier: 'Pacific/Majuro',
        countryCode: 'MH',
        latitude: '7.15',
        longitude: '171.2',
      },
      {
        identifier: 'Pacific/Marquesas',
        countryCode: 'PF',
        latitude: '-9',
        longitude: '-139.5',
      },
      {
        identifier: 'Pacific/Midway',
        countryCode: 'UM',
        latitude: '28.21666',
        longitude: '-177.36667',
      },
      {
        identifier: 'Pacific/Nauru',
        countryCode: 'NR',
        latitude: '-0.51667',
        longitude: '166.91666',
      },
      {
        identifier: 'Pacific/Niue',
        countryCode: 'NU',
        latitude: '-19.01667',
        longitude: '-169.91667',
      },
      {
        identifier: 'Pacific/Norfolk',
        countryCode: 'NF',
        latitude: '-29.05',
        longitude: '167.96666',
      },
      {
        identifier: 'Pacific/Noumea',
        countryCode: 'NC',
        latitude: '-22.26667',
        longitude: '166.45',
      },
      {
        identifier: 'Pacific/Pago_Pago',
        countryCode: 'AS',
        latitude: '-14.26667',
        longitude: '-170.7',
      },
      {
        identifier: 'Pacific/Palau',
        countryCode: 'PW',
        latitude: '7.33333',
        longitude: '134.48333',
      },
      {
        identifier: 'Pacific/Pitcairn',
        countryCode: 'PN',
        latitude: '-25.06667',
        longitude: '-130.08334',
      },
      {
        identifier: 'Pacific/Pohnpei',
        countryCode: 'FM',
        latitude: '6.96666',
        longitude: '158.21666',
      },
      {
        identifier: 'Pacific/Port_Moresby',
        countryCode: 'PG',
        latitude: '-9.5',
        longitude: '147.16666',
      },
      {
        identifier: 'Pacific/Rarotonga',
        countryCode: 'CK',
        latitude: '-21.23334',
        longitude: '-159.76667',
      },
      {
        identifier: 'Pacific/Saipan',
        countryCode: 'MP',
        latitude: '15.2',
        longitude: '145.75',
      },
      {
        identifier: 'Pacific/Tahiti',
        countryCode: 'PF',
        latitude: '-17.53334',
        longitude: '-149.56667',
      },
      {
        identifier: 'Pacific/Tarawa',
        countryCode: 'KI',
        latitude: '1.41666',
        longitude: '173',
      },
      {
        identifier: 'Pacific/Tongatapu',
        countryCode: 'TO',
        latitude: '-21.16667',
        longitude: '-175.16667',
      },
      {
        identifier: 'Pacific/Wake',
        countryCode: 'UM',
        latitude: '19.28333',
        longitude: '166.61666',
      },
      {
        identifier: 'Pacific/Wallis',
        countryCode: 'WF',
        latitude: '-13.3',
        longitude: '-176.16667',
      },
      {
        identifier: 'UTC',
        countryCode: '??',
        latitude: '0',
        longitude: '0',
      },
    ];
  }
}
