/**
 * This file was auto generated, please do not edit it directly.
 **/
export interface CIOMarketingEventCountTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isFewerThanFive: boolean;
  isMoreThanThirty: boolean;
  isBetweenFiveAndThirty: boolean;
}
export interface CIOMarketingEventTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isBrandAwarenessEvents: boolean;
  isTradeShows: boolean;
  isConferences: boolean;
  isRoadshows: boolean;
  isInternalMeetings: boolean;
  isRecruitingEvents: boolean;
  isFundraisingEvents: boolean;
}
export interface CIOMarketingIndustryTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isAgency: boolean;
  isEducation: boolean;
  isFinance: boolean;
  isSportsAndEntertainment: boolean;
  isTechnology: boolean;
  isOther: boolean;
}
export interface EventDateFilterTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isCurrentFuture: boolean;
  isPastAll: boolean;
  isPast3Months: boolean;
  isPast3MonthsAndFuture: boolean;
  isPast6Months: boolean;
}
export interface EventMessageSlugTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isEventPublicURL: boolean;
  isEventName: boolean;
  isEventEmail: boolean;
  isEventLocationName: boolean;
  isEventLocationAddress: boolean;
  isEventDescription: boolean;
  isEventFacebook: boolean;
  isEventTwitter: boolean;
  isEventInstagram: boolean;
  isEventStartDateTime: boolean;
  isEventStartDate: boolean;
  isEventStartTime: boolean;
  isEventStartDateTimeShort: boolean;
  isEventStartDateShort: boolean;
  isEventStartTimeShort: boolean;
  isEventStartDateTimeLong: boolean;
  isEventStartDateLong: boolean;
  isEventStartTimeLong: boolean;
  isEventEndDateTime: boolean;
  isEventEndDate: boolean;
  isEventEndTime: boolean;
  isEventEndDateTimeShort: boolean;
  isEventEndDateShort: boolean;
  isEventEndTimeShort: boolean;
  isEventEndDateTimeLong: boolean;
  isEventEndDateLong: boolean;
  isEventEndTimeLong: boolean;
}
export interface EventMessageTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isIntroduction: boolean;
  isOpening: boolean;
  isClosing: boolean;
  isConfirmation: boolean;
  isDeclination: boolean;
  isSoldOut: boolean;
  isReveal: boolean;
  isDisclaimer: boolean;
  isResponseRestriction: boolean;
  defaultValue: any;
  value: any;
}
export interface EventTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isEventFarm: boolean;
  isCio: boolean;
  isListly: boolean;
  isDnc: boolean;
  isRnc: boolean;
  isRslc: boolean;
  isSundance: boolean;
}
export interface MapSourceTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isGoogle: boolean;
  isYahoo: boolean;
  isBing: boolean;
}
export interface QuestionContextTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isRegistration: boolean;
  isLeadCapture: boolean;
}
export interface QuestionTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isCheckbox: boolean;
  isRadio: boolean;
  isMulti: boolean;
  isText: boolean;
  isSelect: boolean;
  isDate: boolean;
  isWaiver: boolean;
}
export interface ThemeColorTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isAlert: boolean;
  isBackground: boolean;
  isFont: boolean;
  isPrimary: boolean;
  isPrimaryAlt: boolean;
}
export interface ThemeFontFamilyTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isTimes: boolean;
}
export interface ThemeNameTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isMaterial: boolean;
}
export interface TrackingScriptTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isRegistration: boolean;
  isConfirmation: boolean;
  value: any;
}

export class Event {
  CIOMarketingEventCountType(): CIOMarketingEventCountTypeInterface[] {
    return [
      {
        slug: 'fewer-than-5',
        name: 'Fewer than 5',
        description: null,
        isFewerThanFive: true,
        isMoreThanThirty: false,
        isBetweenFiveAndThirty: false,
      },
      {
        slug: 'between-5-and-30',
        name: 'Between 5 and 30',
        description: null,
        isFewerThanFive: false,
        isMoreThanThirty: false,
        isBetweenFiveAndThirty: true,
      },
      {
        slug: 'more-than-30',
        name: 'More than 30',
        description: null,
        isFewerThanFive: false,
        isMoreThanThirty: true,
        isBetweenFiveAndThirty: false,
      },
    ];
  }

  CIOMarketingEventType(): CIOMarketingEventTypeInterface[] {
    return [
      {
        slug: 'brand-awareness-events',
        name: 'Brand Awareness Events',
        description: null,
        isBrandAwarenessEvents: true,
        isTradeShows: false,
        isConferences: false,
        isRoadshows: false,
        isInternalMeetings: false,
        isRecruitingEvents: false,
        isFundraisingEvents: false,
      },
      {
        slug: 'trade-shows',
        name: 'Trade Shows',
        description: null,
        isBrandAwarenessEvents: false,
        isTradeShows: true,
        isConferences: false,
        isRoadshows: false,
        isInternalMeetings: false,
        isRecruitingEvents: false,
        isFundraisingEvents: false,
      },
      {
        slug: 'conferences',
        name: 'Conferences',
        description: null,
        isBrandAwarenessEvents: false,
        isTradeShows: false,
        isConferences: true,
        isRoadshows: false,
        isInternalMeetings: false,
        isRecruitingEvents: false,
        isFundraisingEvents: false,
      },
      {
        slug: 'roadshows',
        name: 'Roadshows',
        description: null,
        isBrandAwarenessEvents: false,
        isTradeShows: false,
        isConferences: false,
        isRoadshows: true,
        isInternalMeetings: false,
        isRecruitingEvents: false,
        isFundraisingEvents: false,
      },
      {
        slug: 'internal-meetings',
        name: 'Internal Meetings',
        description: null,
        isBrandAwarenessEvents: false,
        isTradeShows: false,
        isConferences: false,
        isRoadshows: false,
        isInternalMeetings: true,
        isRecruitingEvents: false,
        isFundraisingEvents: false,
      },
      {
        slug: 'recruiting-events',
        name: 'Recruiting Events',
        description: null,
        isBrandAwarenessEvents: false,
        isTradeShows: false,
        isConferences: false,
        isRoadshows: false,
        isInternalMeetings: false,
        isRecruitingEvents: true,
        isFundraisingEvents: false,
      },
      {
        slug: 'fundraising-events',
        name: 'Fundraising Events',
        description: null,
        isBrandAwarenessEvents: false,
        isTradeShows: false,
        isConferences: false,
        isRoadshows: false,
        isInternalMeetings: false,
        isRecruitingEvents: false,
        isFundraisingEvents: true,
      },
    ];
  }

  CIOMarketingIndustryType(): CIOMarketingIndustryTypeInterface[] {
    return [
      {
        slug: 'consumer-goods',
        name: 'Consumer Goods',
        description: null,
        isAgency: false,
        isEducation: false,
        isFinance: false,
        isSportsAndEntertainment: false,
        isTechnology: false,
        isOther: false,
      },
      {
        slug: 'agency',
        name: 'Agency',
        description: null,
        isAgency: true,
        isEducation: false,
        isFinance: false,
        isSportsAndEntertainment: false,
        isTechnology: false,
        isOther: false,
      },
      {
        slug: 'education',
        name: 'Education',
        description: null,
        isAgency: false,
        isEducation: true,
        isFinance: false,
        isSportsAndEntertainment: false,
        isTechnology: false,
        isOther: false,
      },
      {
        slug: 'finance',
        name: 'Finance',
        description: null,
        isAgency: false,
        isEducation: false,
        isFinance: true,
        isSportsAndEntertainment: false,
        isTechnology: false,
        isOther: false,
      },
      {
        slug: 'sports-and-entertainment',
        name: 'Sports and Entertainment',
        description: null,
        isAgency: false,
        isEducation: false,
        isFinance: false,
        isSportsAndEntertainment: true,
        isTechnology: false,
        isOther: false,
      },
      {
        slug: 'technology',
        name: 'Technology',
        description: null,
        isAgency: false,
        isEducation: false,
        isFinance: false,
        isSportsAndEntertainment: false,
        isTechnology: true,
        isOther: false,
      },
      {
        slug: 'other',
        name: 'Other',
        description: null,
        isAgency: false,
        isEducation: false,
        isFinance: false,
        isSportsAndEntertainment: false,
        isTechnology: false,
        isOther: true,
      },
    ];
  }

  EventDateFilterType(): EventDateFilterTypeInterface[] {
    return [
      {
        slug: 'current-future',
        name: 'Current &amp; Future Events',
        description: 'This will show you all your future and current events.',
        isCurrentFuture: true,
        isPastAll: false,
        isPast3Months: false,
        isPast3MonthsAndFuture: false,
        isPast6Months: false,
      },
      {
        slug: 'past-all',
        name: 'All Past Events',
        description: null,
        isCurrentFuture: false,
        isPastAll: true,
        isPast3Months: false,
        isPast3MonthsAndFuture: false,
        isPast6Months: false,
      },
      {
        slug: 'past-3-months',
        name: 'Past 3 Months',
        description: null,
        isCurrentFuture: false,
        isPastAll: false,
        isPast3Months: true,
        isPast3MonthsAndFuture: false,
        isPast6Months: false,
      },
      {
        slug: 'past-3-months-and-future',
        name: 'Past 3 Months and Future Events',
        description:
          'This will show you past 3 months events and all future events',
        isCurrentFuture: false,
        isPastAll: false,
        isPast3Months: false,
        isPast3MonthsAndFuture: true,
        isPast6Months: false,
      },
      {
        slug: 'past-6-months',
        name: 'Past 6 Months',
        description: null,
        isCurrentFuture: false,
        isPastAll: false,
        isPast3Months: false,
        isPast3MonthsAndFuture: false,
        isPast6Months: true,
      },
    ];
  }

  EventMessageSlugType(): EventMessageSlugTypeInterface[] {
    return [
      {
        slug: '{{eventPublicUrl}}',
        name: 'Event Public URL',
        description: null,
        isEventPublicURL: true,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventName}}',
        name: 'Event Name',
        description: null,
        isEventPublicURL: false,
        isEventName: true,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEmail}}',
        name: 'Event Email',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: true,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventLocationName}}',
        name: 'Event Location Name',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: true,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventLocationAddress}}',
        name: 'Event Location Address',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: true,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventDescription}}',
        name: 'Event Description',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: true,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventFacebook}}',
        name: 'Event Facebook',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: true,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventTwitter}}',
        name: 'Event Twitter',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: true,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventInstagram}}',
        name: 'Event Instagram',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: true,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartDateTime}}',
        name: 'Event Start Date - Time',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: true,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartDate}}',
        name: 'Event Start Date',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: true,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartTime}}',
        name: 'Event Start Time',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: true,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartDateTimeShort}}',
        name: 'Event Start Date - Time (Short)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: true,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartDateShort}}',
        name: 'Event Start Date (Short)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: true,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartDateShort}}',
        name: 'Event Start Date (Short)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: true,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartDateTimeLong}}',
        name: 'Event Start Date - Time (Long)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: true,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartDateLong}}',
        name: 'Event Start Date (Long)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: true,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventStartTimeLong}}',
        name: 'Event Start Time (Long)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: true,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndDateTime}}',
        name: 'Event End Date - Time',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: true,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndDate}}',
        name: 'Event End Date',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: true,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndTime}}',
        name: 'Event End Time',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: true,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndDateTimeShort}}',
        name: 'Event End Date - Time (Short)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: true,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndDateShort}}',
        name: 'Event End Date (Short)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: true,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndTimeShort}}',
        name: 'Event End Time (Short)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: true,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndDateTimeLong}}',
        name: 'Event End Date - Time (Long)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: true,
        isEventEndDateLong: false,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndDateLong}}',
        name: 'Event End Date (Long)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: true,
        isEventEndTimeLong: false,
      },
      {
        slug: '{{eventEndTimeLong}}',
        name: 'Event End Time (Long)',
        description: null,
        isEventPublicURL: false,
        isEventName: false,
        isEventEmail: false,
        isEventLocationName: false,
        isEventLocationAddress: false,
        isEventDescription: false,
        isEventFacebook: false,
        isEventTwitter: false,
        isEventInstagram: false,
        isEventStartDateTime: false,
        isEventStartDate: false,
        isEventStartTime: false,
        isEventStartDateTimeShort: false,
        isEventStartDateShort: false,
        isEventStartTimeShort: false,
        isEventStartDateTimeLong: false,
        isEventStartDateLong: false,
        isEventStartTimeLong: false,
        isEventEndDateTime: false,
        isEventEndDate: false,
        isEventEndTime: false,
        isEventEndDateTimeShort: false,
        isEventEndDateShort: false,
        isEventEndTimeShort: false,
        isEventEndDateTimeLong: false,
        isEventEndDateLong: false,
        isEventEndTimeLong: true,
      },
    ];
  }

  EventMessageType(): EventMessageTypeInterface[] {
    return [
      {
        slug: 'additional',
        name: 'Registration Introduction',
        description:
          'Displayed to guests at the beginning of the purchase/registration/RSVP process.',
        isIntroduction: true,
        isOpening: false,
        isClosing: false,
        isConfirmation: false,
        isDeclination: false,
        isSoldOut: false,
        isReveal: false,
        isDisclaimer: false,
        isResponseRestriction: false,
        defaultValue: null,
        value: null,
      },
      {
        slug: 'before-opening',
        name: 'Prior To Opening',
        description:
          'Displayed as a placeholder for the registration or purchase form before the event goes live and tickets become available.',
        isIntroduction: false,
        isOpening: true,
        isClosing: false,
        isConfirmation: false,
        isDeclination: false,
        isSoldOut: false,
        isReveal: false,
        isDisclaimer: false,
        isResponseRestriction: false,
        defaultValue:
          'Tickets for {{eventName}} are not yet available—please check back in the near future!',
        value: null,
      },
      {
        slug: 'after-closing',
        name: 'After Closing',
        description:
          'Displayed as a placeholder for the registration or purchase form once registration has closed for an event.',
        isIntroduction: false,
        isOpening: false,
        isClosing: true,
        isConfirmation: false,
        isDeclination: false,
        isSoldOut: false,
        isReveal: false,
        isDisclaimer: false,
        isResponseRestriction: false,
        defaultValue:
          'Tickets for {{eventName}} are no longer available through this website. Please check with the event organizers to find out if tickets are available elsewhere.',
        value: null,
      },
      {
        slug: 'confirmation',
        name: 'Confirmation',
        description:
          'Displayed on the confirmation screen after a successful purchase, registration or RSVP.',
        isIntroduction: false,
        isOpening: false,
        isClosing: false,
        isConfirmation: true,
        isDeclination: false,
        isSoldOut: false,
        isReveal: false,
        isDisclaimer: false,
        isResponseRestriction: false,
        defaultValue:
          'You&#039;re all set. We look forward to seeing you soon!',
        value: null,
      },
      {
        slug: 'declination',
        name: 'Declination',
        description:
          'Displayed on the confirmation screen after a guest declines their RSVP.',
        isIntroduction: false,
        isOpening: false,
        isClosing: false,
        isConfirmation: false,
        isDeclination: true,
        isSoldOut: false,
        isReveal: false,
        isDisclaimer: false,
        isResponseRestriction: false,
        defaultValue:
          'Thanks for your response. We&#039;re sorry we&#039;ll miss you!',
        value: null,
      },
      {
        slug: 'sold-out',
        name: 'Sold-Out',
        description:
          'Displayed for any event access type (General Admission, VIP, etc.) that is either sold out or at capacity.',
        isIntroduction: false,
        isOpening: false,
        isClosing: false,
        isConfirmation: false,
        isDeclination: false,
        isSoldOut: true,
        isReveal: false,
        isDisclaimer: false,
        isResponseRestriction: false,
        defaultValue: '',
        value: null,
      },
      {
        slug: 'reveal',
        name: 'Reveal',
        description:
          'If Invitation Reveal is enabled, the &quot;Reveal Message&quot; will display when a guest begins the registration process.',
        isIntroduction: false,
        isOpening: false,
        isClosing: false,
        isConfirmation: false,
        isDeclination: false,
        isSoldOut: false,
        isReveal: true,
        isDisclaimer: false,
        isResponseRestriction: false,
        defaultValue:
          'Tickets for {{eventName}} are no longer available. If you feel you have reached this page in error, please contact the event organizers for more information.',
        value: null,
      },
      {
        slug: 'disclaimer',
        name: 'Disclaimer',
        description:
          'If you have created a Waiver question, this message will display as part of the purchase, registration, and RSVP process. The guest must check the disclaimer box to complete registration.',
        isIntroduction: false,
        isOpening: false,
        isClosing: false,
        isConfirmation: false,
        isDeclination: false,
        isSoldOut: false,
        isReveal: false,
        isDisclaimer: true,
        isResponseRestriction: false,
        defaultValue: null,
        value: null,
      },
      {
        slug: 'response-restriction',
        name: 'Response Restriction',
        description:
          'If the Event Setting “Guest can change response” is “NO”, this message will display for any registered guest who clicks the invitation link again.',
        isIntroduction: false,
        isOpening: false,
        isClosing: false,
        isConfirmation: false,
        isDeclination: false,
        isSoldOut: false,
        isReveal: false,
        isDisclaimer: false,
        isResponseRestriction: true,
        defaultValue: null,
        value: null,
      },
    ];
  }

  EventType(): EventTypeInterface[] {
    return [
      {
        slug: 'eventfarm',
        name: 'Event Farm',
        description: null,
        isEventFarm: true,
        isCio: false,
        isListly: false,
        isDnc: false,
        isRnc: false,
        isRslc: false,
        isSundance: false,
      },
      {
        slug: 'cio',
        name: 'Check-in-Only',
        description: null,
        isEventFarm: false,
        isCio: true,
        isListly: false,
        isDnc: false,
        isRnc: false,
        isRslc: false,
        isSundance: false,
      },
      {
        slug: 'listly',
        name: 'Listly',
        description: null,
        isEventFarm: false,
        isCio: false,
        isListly: true,
        isDnc: false,
        isRnc: false,
        isRslc: false,
        isSundance: false,
      },
      {
        slug: 'dnc',
        name: 'DNC',
        description: null,
        isEventFarm: false,
        isCio: false,
        isListly: false,
        isDnc: true,
        isRnc: false,
        isRslc: false,
        isSundance: false,
      },
      {
        slug: 'rnc',
        name: 'RNC',
        description: null,
        isEventFarm: false,
        isCio: false,
        isListly: false,
        isDnc: false,
        isRnc: true,
        isRslc: false,
        isSundance: false,
      },
      {
        slug: 'rslc',
        name: 'RSLC',
        description: null,
        isEventFarm: false,
        isCio: false,
        isListly: false,
        isDnc: false,
        isRnc: false,
        isRslc: true,
        isSundance: false,
      },
      {
        slug: 'sundance',
        name: 'Sundance',
        description: null,
        isEventFarm: false,
        isCio: false,
        isListly: false,
        isDnc: false,
        isRnc: false,
        isRslc: false,
        isSundance: true,
      },
    ];
  }

  MapSourceType(): MapSourceTypeInterface[] {
    return [
      {
        slug: 'google',
        name: 'Google',
        description: 'Google Maps',
        isGoogle: true,
        isYahoo: false,
        isBing: false,
      },
      {
        slug: 'yahoo',
        name: 'Yahoo',
        description: 'Yahoo Maps',
        isGoogle: false,
        isYahoo: true,
        isBing: false,
      },
      {
        slug: 'bing',
        name: 'Bing',
        description: 'Bing Maps',
        isGoogle: false,
        isYahoo: false,
        isBing: true,
      },
    ];
  }

  QuestionContextType(): QuestionContextTypeInterface[] {
    return [
      {
        slug: 'registration',
        name: 'Registration',
        description: null,
        isRegistration: true,
        isLeadCapture: false,
      },
      {
        slug: 'lead',
        name: 'Lead Capture',
        description: null,
        isRegistration: false,
        isLeadCapture: true,
      },
    ];
  }

  QuestionType(): QuestionTypeInterface[] {
    return [
      {
        slug: 'checkbox',
        name: 'Checkbox',
        description: null,
        isCheckbox: true,
        isRadio: false,
        isMulti: false,
        isText: false,
        isSelect: false,
        isDate: false,
        isWaiver: false,
      },
      {
        slug: 'radio',
        name: 'Radio',
        description: null,
        isCheckbox: false,
        isRadio: true,
        isMulti: false,
        isText: false,
        isSelect: false,
        isDate: false,
        isWaiver: false,
      },
      {
        slug: 'multi',
        name: 'Multi',
        description: null,
        isCheckbox: false,
        isRadio: false,
        isMulti: true,
        isText: false,
        isSelect: false,
        isDate: false,
        isWaiver: false,
      },
      {
        slug: 'text',
        name: 'Text',
        description: null,
        isCheckbox: false,
        isRadio: false,
        isMulti: false,
        isText: true,
        isSelect: false,
        isDate: false,
        isWaiver: false,
      },
      {
        slug: 'select',
        name: 'Select',
        description: null,
        isCheckbox: false,
        isRadio: false,
        isMulti: false,
        isText: false,
        isSelect: true,
        isDate: false,
        isWaiver: false,
      },
      {
        slug: 'date',
        name: 'Date',
        description: null,
        isCheckbox: false,
        isRadio: false,
        isMulti: false,
        isText: false,
        isSelect: false,
        isDate: true,
        isWaiver: false,
      },
      {
        slug: 'waiver',
        name: 'Waiver',
        description: null,
        isCheckbox: false,
        isRadio: false,
        isMulti: false,
        isText: false,
        isSelect: false,
        isDate: false,
        isWaiver: true,
      },
    ];
  }

  ThemeColorType(): ThemeColorTypeInterface[] {
    return [
      {
        slug: 'alert',
        name: 'Alert Color',
        description: '#df260a',
        isAlert: true,
        isBackground: false,
        isFont: false,
        isPrimary: false,
        isPrimaryAlt: false,
      },
      {
        slug: 'background',
        name: 'Background Color',
        description: '#ffffff',
        isAlert: false,
        isBackground: true,
        isFont: false,
        isPrimary: false,
        isPrimaryAlt: false,
      },
      {
        slug: 'font',
        name: 'Font Color',
        description: '#444444',
        isAlert: false,
        isBackground: false,
        isFont: true,
        isPrimary: false,
        isPrimaryAlt: false,
      },
      {
        slug: 'primary',
        name: 'Primary Color',
        description: '#5085F0',
        isAlert: false,
        isBackground: false,
        isFont: false,
        isPrimary: true,
        isPrimaryAlt: false,
      },
      {
        slug: 'primaryAlt',
        name: 'Primary Alt Color',
        description: '#A2AEBB',
        isAlert: false,
        isBackground: false,
        isFont: false,
        isPrimary: false,
        isPrimaryAlt: true,
      },
    ];
  }

  ThemeFontFamilyType(): ThemeFontFamilyTypeInterface[] {
    return [
      {
        slug: 'times',
        name: 'Times New Roman',
        description: null,
        isTimes: true,
      },
    ];
  }

  ThemeNameType(): ThemeNameTypeInterface[] {
    return [
      {
        slug: 'material',
        name: 'Material Design',
        description: null,
        isMaterial: true,
      },
    ];
  }

  TrackingScriptType(): TrackingScriptTypeInterface[] {
    return [
      {
        slug: 'registration_tracking_script',
        name: 'Registration Tracking Script',
        description:
          'Provide the tracking script for your analytics tool, such as Google Analytics, to collect data on visitors to the registration form.',
        isRegistration: true,
        isConfirmation: false,
        value: null,
      },
      {
        slug: 'confirmation_tracking_script',
        name: 'Confirmation Tracking Script',
        description:
          'Provide the tracking script for your analytics tool, such as Google Analytics, to collect data on visitors to the confirmation page.',
        isRegistration: false,
        isConfirmation: true,
        value: null,
      },
    ];
  }
}
