/**
 * This file was auto generated, please do not edit it directly.
 **/
export interface FeatureTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isSalesforce: boolean;
  isApiAccess: boolean;
  isMarketo: boolean;
  isEmailMasking: boolean;
  isWhiteLabeling: boolean;
  isAgents: boolean;
  isVisaCheckout: boolean;
  isCanvas: boolean;
  isHarvesterPPP: boolean;
  isAccessControlEFx: boolean;
  isAthleteBagEFx: boolean;
  isConciergeEFx: boolean;
  isDigitalMemoryBankEFx: boolean;
  isGuestInfoEFx: boolean;
  isMessagingEFx: boolean;
  isSmsQuizEFx: boolean;
  isProductPickupEFx: boolean;
  isRaffleEFx: boolean;
  isReservationEFx: boolean;
  isRoamingPhotogEFx: boolean;
  isSmartBarEFx: boolean;
  isTeamsEFx: boolean;
  isEventApp: boolean;
  isChildEvents: boolean;
  isWaitlist: boolean;
  isVirbela: boolean;
  isWebConference: boolean;
  isQuestionLogic: boolean;
  isHealthPass: boolean;
}
export interface PoolAllotmentTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isListly: boolean;
  isCIO: boolean;
  isEventFarm: boolean;
}
export interface PoolContactTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isFull: boolean;
  isCreate: boolean;
}
export interface PoolContractTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isCIO: boolean;
  isIntro: boolean;
  isTrial: boolean;
  isPro: boolean;
  isPremier: boolean;
  isPremierPlus: boolean;
  isCustom: boolean;
  isInternal: boolean;
}
export interface PoolWebhookTypeInterface {
  slug: string;
  name: string;
  description?: string;
  isCheckin: boolean;
}

export class Pool {
  FeatureType(): FeatureTypeInterface[] {
    return [
      {
        slug: 'salesforce',
        name: 'Salesforce',
        description: null,
        isSalesforce: true,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'apiaccess',
        name: 'API Access',
        description: null,
        isSalesforce: false,
        isApiAccess: true,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'marketo',
        name: 'Marketo',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: true,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'emailmasking',
        name: 'Email Masking',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: true,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'whitelabeling',
        name: 'White Labeling',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: true,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'agents',
        name: 'Agents',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: true,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'visacheckout',
        name: 'VisaCheckout',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: true,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'canvas',
        name: 'Canvas',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: true,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'harvester',
        name: 'Harvester (PPP)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: true,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'accesscontrol-efx',
        name: 'Access Control (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: true,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'athletebag-efx',
        name: 'Athlete Bag (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: true,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'concierge-efx',
        name: 'Concierge (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: true,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'digitalmemorybank-efx',
        name: 'Digital Memory Bank (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: true,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'guestinfo-efx',
        name: 'Guest Info (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: true,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'messaging-efx',
        name: 'Messaging (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: true,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'smsquiz-efx',
        name: 'SMS Quiz (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: true,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'productpickup-efx',
        name: 'Product Pickup (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: true,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'raffle-efx',
        name: 'Raffle (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: true,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'reservation-efx',
        name: 'Reservation (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: true,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'roamingphotog-efx',
        name: 'Roaming Photog (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: true,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'smartbar-efx',
        name: 'SmartBar (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: true,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'teams-efx',
        name: 'Teams (EFx)',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: true,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'event-app',
        name: 'Event App',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: true,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'child-events',
        name: 'Child Events',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: true,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'waitlist',
        name: 'Waitlist',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: true,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'virbela',
        name: 'Virbela',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: true,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'web-conference',
        name: 'Web Conference',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: true,
        isQuestionLogic: false,
        isHealthPass: false,
      },
      {
        slug: 'health-pass',
        name: 'Health Pass',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: false,
        isHealthPass: true,
      },
      {
        slug: 'question-logic',
        name: 'Question Logic',
        description: null,
        isSalesforce: false,
        isApiAccess: false,
        isMarketo: false,
        isEmailMasking: false,
        isWhiteLabeling: false,
        isAgents: false,
        isVisaCheckout: false,
        isCanvas: false,
        isHarvesterPPP: false,
        isAccessControlEFx: false,
        isAthleteBagEFx: false,
        isConciergeEFx: false,
        isDigitalMemoryBankEFx: false,
        isGuestInfoEFx: false,
        isMessagingEFx: false,
        isSmsQuizEFx: false,
        isProductPickupEFx: false,
        isRaffleEFx: false,
        isReservationEFx: false,
        isRoamingPhotogEFx: false,
        isSmartBarEFx: false,
        isTeamsEFx: false,
        isEventApp: false,
        isChildEvents: false,
        isWaitlist: false,
        isVirbela: false,
        isWebConference: false,
        isQuestionLogic: true,
        isHealthPass: false,
      },
    ];
  }

  PoolAllotmentType(): PoolAllotmentTypeInterface[] {
    return [
      {
        slug: 'listly',
        name: 'Listly',
        description: null,
        isListly: true,
        isCIO: false,
        isEventFarm: false,
      },
      {
        slug: 'cio',
        name: 'CIO',
        description: null,
        isListly: false,
        isCIO: true,
        isEventFarm: false,
      },
      {
        slug: 'eventfarm',
        name: 'EventFarm',
        description: null,
        isListly: false,
        isCIO: false,
        isEventFarm: true,
      },
    ];
  }

  PoolContactType(): PoolContactTypeInterface[] {
    return [
      {
        slug: 'full',
        name: 'Team Manager',
        description: null,
        isFull: true,
        isCreate: false,
      },
      {
        slug: 'create',
        name: 'Event Create Only',
        description: null,
        isFull: false,
        isCreate: true,
      },
    ];
  }

  PoolContractType(): PoolContractTypeInterface[] {
    return [
      {
        slug: 'cio',
        name: 'CIO',
        description: null,
        isCIO: true,
        isIntro: false,
        isTrial: false,
        isPro: false,
        isPremier: false,
        isPremierPlus: false,
        isCustom: false,
        isInternal: false,
      },
      {
        slug: 'intro',
        name: 'Intro',
        description: null,
        isCIO: false,
        isIntro: true,
        isTrial: false,
        isPro: false,
        isPremier: false,
        isPremierPlus: false,
        isCustom: false,
        isInternal: false,
      },
      {
        slug: 'trial',
        name: 'Trial',
        description: null,
        isCIO: false,
        isIntro: false,
        isTrial: true,
        isPro: false,
        isPremier: false,
        isPremierPlus: false,
        isCustom: false,
        isInternal: false,
      },
      {
        slug: 'pro',
        name: 'Pro',
        description: null,
        isCIO: false,
        isIntro: false,
        isTrial: false,
        isPro: true,
        isPremier: false,
        isPremierPlus: false,
        isCustom: false,
        isInternal: false,
      },
      {
        slug: 'premier',
        name: 'Premier',
        description: null,
        isCIO: false,
        isIntro: false,
        isTrial: false,
        isPro: false,
        isPremier: true,
        isPremierPlus: false,
        isCustom: false,
        isInternal: false,
      },
      {
        slug: 'premierPlus',
        name: 'Premier Plus',
        description: null,
        isCIO: false,
        isIntro: false,
        isTrial: false,
        isPro: false,
        isPremier: false,
        isPremierPlus: true,
        isCustom: false,
        isInternal: false,
      },
      {
        slug: 'custom',
        name: 'Custom',
        description: null,
        isCIO: false,
        isIntro: false,
        isTrial: false,
        isPro: false,
        isPremier: false,
        isPremierPlus: false,
        isCustom: true,
        isInternal: false,
      },
      {
        slug: 'internal',
        name: 'Internal',
        description: null,
        isCIO: false,
        isIntro: false,
        isTrial: false,
        isPro: false,
        isPremier: false,
        isPremierPlus: false,
        isCustom: false,
        isInternal: true,
      },
    ];
  }

  PoolWebhookType(): PoolWebhookTypeInterface[] {
    return [
      {
        slug: 'checkin',
        name: 'Check-In',
        description: null,
        isCheckin: true,
      },
    ];
  }
}
